// GENERATED by scripts/gen-exports.mjs — do not edit.
//
// The public surface of this package. `app-ui` aliases `showcase` to this
// source tree, so everything below is API for another app.
//
// To change what is exported, edit src/lib/exports.manifest.json and run
// `npm run gen:exports`. Paths are resolved from the filesystem, so moving a
// file between folders needs no edit here or there.

// ── Breakpoints ──────────────────────────────────────────────────────────────
export { BREAKPOINTS } from './breakpoints.js';
export type { BreakpointKey } from './breakpoints.js';
export { useBreakpoint } from './useBreakpoint.svelte.js';

// ── Icons ────────────────────────────────────────────────────────────────────
export { default as Icon, ICONS } from './icons/Icon.svelte';
export type { IconName } from './icons/Icon.svelte';

// The brand mark at full fidelity — two-tone, hollowed core, mesh footprint.
// `<Icon name="armornet" />` is the single-weight version for small sizes.
export { default as ArmornetCrest } from './icons/ArmornetCrest.svelte';

// The same crest cut hub-and-spoke, out of the server/node glyph's language.
export { default as ArmornetCrestHub } from './icons/ArmornetCrestHub.svelte';
export { default as ArmornetCrestChrome } from './icons/ArmornetCrestChrome.svelte';

// Agent-mode node silhouettes — resolve a mode string to its glyph markup
// (defaults to the Terminal glyph when the mode has no assigned outline).
export { glyphForMode, labelForMode, TERMINAL_GLYPH } from './icons/mode-tool-icons.js';

// The agent-mode catalog (generated from agent/modes.yaml) — key, label, desc,
// colour and glyph per mode, so a consumer can represent every mode the platform
// runs, not just the ones with live agents.
export { MODES, MODE_KEYS } from './mesh-studio/modes.gen.js';
export type { ModeMeta } from './mesh-studio/modes.gen.js';

// ── Primitives ───────────────────────────────────────────────────────────────
export { default as Button } from './primitives/actions/Button.svelte';
export type {
	ButtonVariant,
	ButtonSize,
	ButtonShape,
	ButtonTone
} from './primitives/actions/Button.svelte';
export { default as IconButton } from './primitives/actions/IconButton.svelte';
export type { IconButtonVariant } from './primitives/actions/IconButton.svelte';
export { default as ActionsMenu } from './primitives/actions/ActionsMenu.svelte';
export { ACTIONS_MENU_DISMISS, resolveDismiss } from './primitives/actions/ActionsMenu.svelte';
export type {
	ActionMenuItem,
	ActionMenuAction,
	ActionMenuHeader,
	ActionMenuSeparator,
	ActionsMenuPlacement,
	ActionsMenuDismiss,
	ActionsMenuDismissConfig,
	ActionsMenuExit
} from './primitives/actions/ActionsMenu.svelte';
export { default as ExportMenu } from './primitives/actions/ExportMenu.svelte';
export type { ExportFormat } from './primitives/actions/ExportMenu.svelte';
export { default as Chip } from './primitives/status/Chip.svelte';
export type { ChipColor, ChipLook } from './primitives/status/Chip.svelte';
export { default as EdgeToolbarCard } from './primitives/cards/EdgeToolbarCard.svelte';
export { default as Tile } from './primitives/chrome/Tile.svelte';
export type { TileVariant } from './primitives/chrome/Tile.svelte';
export { default as StatCard } from './primitives/cards/StatCard.svelte';
export type { StatCardVariant } from './primitives/cards/StatCard.svelte';
export { default as DocCard } from './primitives/cards/DocCard.svelte';
export type { DocCardColor, DocCardStatus, DocCardAuthor } from './primitives/cards/DocCard.svelte';
export { default as HudCard } from './primitives/cards/HudCard.svelte';
export { default as CompositeCard } from './primitives/cards/CompositeCard.svelte';
export type { CompositeCardItem } from './primitives/cards/card.types.js';
export { default as PricingCard } from './primitives/cards/PricingCard.svelte';
export { default as StatusDot } from './primitives/status/StatusDot.svelte';
export { default as StatusBadge } from './primitives/status/StatusBadge.svelte';
export type { StatusLevel } from './primitives/status/StatusDot.svelte';
export { default as Checkbox } from './primitives/forms/Checkbox.svelte';
export { default as Toggle } from './primitives/forms/Toggle.svelte';
export type { ToggleVariant } from './primitives/forms/toggle.types.js';
export { default as Input } from './primitives/forms/Input.svelte';
export type { InputType } from './primitives/forms/Input.svelte';
export { default as PasswordInput } from './primitives/forms/PasswordInput.svelte';
export { default as Textarea } from './primitives/forms/Textarea.svelte';
export { default as FormField } from './primitives/forms/FormField.svelte';
export { default as ChipInput } from './primitives/forms/ChipInput.svelte';
export { default as FileUpload } from './primitives/forms/FileUpload.svelte';
export { default as ViewToggle } from './primitives/actions/ViewToggle.svelte';
export type { ViewToggleOption } from './primitives/actions/ViewToggle.svelte';
export { default as SearchInput } from './primitives/forms/SearchInput.svelte';
export { default as CommandPalette } from './primitives/actions/CommandPalette.svelte';
export type { CmdItem, CmdGroup } from './primitives/actions/CommandPalette.svelte';
export { default as Select } from './primitives/forms/Select.svelte';
export type { SelectOption, SelectOptGroup } from './primitives/forms/Select.svelte';
export { default as SettingRow } from './primitives/forms/SettingRow.svelte';
export { default as UserBlock } from './primitives/cards/UserBlock.svelte';
export { default as StatStrip } from './primitives/chrome/StatStrip.svelte';
export type { StatStripItem, StatStripColor } from './primitives/chrome/StatStrip.svelte';
export { default as EcoTabBar } from './primitives/chrome/EcoTabBar.svelte';
export type { EcoTab } from './primitives/chrome/EcoTabBar.svelte';
export { default as DangerBanner } from './primitives/status/DangerBanner.svelte';
export { default as EmptyState } from './primitives/status/EmptyState.svelte';
export type { EmptyStateVariant } from './primitives/status/EmptyState.svelte';
export { default as SectionBar } from './primitives/chrome/SectionBar.svelte';
export { default as HudCorners } from './primitives/chrome/HudCorners.svelte';
export { default as Canvas } from './primitives/canvas/Canvas.svelte';
export { default as MeshMembrane } from './mesh-studio/membrane/MeshMembrane.svelte';
export type {
	MembraneRegistry,
	MembraneProxy,
	MembraneAgent
} from './mesh-studio/membrane/MeshMembrane.svelte';
export { default as CameraControls } from './primitives/canvas/CameraControls.svelte';
export { default as Minimap } from './primitives/canvas/Minimap.svelte';
export { default as SelectionBox } from './primitives/canvas/SelectionBox.svelte';
export type {
	CanvasCamera,
	TourStep,
	TourController,
	CanvasContextValue,
	SelectionHandler
} from './primitives/canvas/canvas-camera.js';
export type {
	MeshNodeType,
	NodeState,
	DataType,
	EdgeStyle,
	Port
} from './primitives/canvas/canvas.types.js';

// Interactive mesh canvas — radial hub, drag/drop, closest-port line routing.
export { default as MeshStudio } from './mesh-studio/MeshStudio.svelte';
export { default as GlobeFrame } from './mesh-studio/globe/GlobeFrame.svelte';
export { default as TerritoryCaps } from './mesh-studio/globe/TerritoryCaps.svelte';
export type { Territory, TerritoryStyle } from './mesh-studio/globe/TerritoryCaps.svelte';
export { default as NodePiece } from './mesh-studio/pieces/NodePiece.svelte';
export { PIECES, box, gable, tooth, prism, octagon } from './mesh-studio/pieces/pieces.js';
export type { Piece, Solid, PieceVert, PieceId } from './mesh-studio/pieces/pieces.js';
export {
	pieceFacets,
	pieceProjector,
	studioFrame,
	band,
	PIECE_LIGHT
} from './mesh-studio/pieces/piece-facets.js';
export type { Facet, FacetOpts } from './mesh-studio/pieces/piece-facets.js';
export { ALL_PIECES, MODE_PIECES, pieceForMode } from './mesh-studio/pieces/piece-catalogue.js';
export { WORKS_PIECES, WORKS_MODE_PIECES } from './mesh-studio/pieces/pieces-works.js';
export { CIVIC_PIECES, CIVIC_MODE_PIECES } from './mesh-studio/pieces/pieces-civic.js';
export type { StudioNode, StudioEdge } from './mesh-studio/studio.types.js';
export { glyphForModes, AGENT_GLYPH } from './icons/mode-tool-icons.js';

// Node sizing + ring placement — a consumer laying out a mesh must size nodes the
// same way MeshStudio draws them, or they overlap.
export {
	packingR,
	silhouetteR,
	labelBox,
	nodeR,
	arcGeom
} from './mesh-studio/layout/mesh-metrics.js';
export type { MetricOpts } from './mesh-studio/layout/mesh-metrics.js';

// Layout physics — pure geometry over circular bodies, with no knowledge of what
// a body stands for. `packRing` seeds a feasible layout; `packInward` draws it in
// around a hub, keeping bodies apart and links legible.
export { packRing, solveRingRadius } from './physics/ring.js';
export type { RingOpts, RingPlacement } from './physics/ring.js';
export { packSunflower, GOLDEN_ANGLE } from './physics/sunflower.js';
export {
	packSphere,
	packSphereClusters,
	solveRadius,
	fibonacciDir,
	capDir,
	capField,
	capRing,
	capRingYaw,
	alignZ,
	spin,
	project,
	projectPoint,
	tangentFrame
} from './physics/sphere.js';

// Ground on a sphere — an elevation field the globe, its nodes and the solids
// standing on them all sample, so they agree about where the surface is.
export {
	makeTerrain,
	terrainLift,
	capMask,
	maskTerrain,
	shapeTerrain,
	contours
} from './physics/terrain.js';
export type {
	Terrain,
	TerrainOpts,
	Relief,
	ContourOpts,
	ContourLine,
	ContourSegment
} from './physics/terrain.js';

// ClusterOpts/ClusterPlacement are declared in both sphere.ts and
// cluster.ts; the barrel has always meant cluster.ts, hence the pin.
export type {
	ClusterOpts as SphereClusterOpts,
	ClusterPlacement as SphereClusterPlacement
} from './physics/cluster.js';

// The sphere's clustering types are named for the same idea as `cluster.ts`'s
// 2D ones, so they carry a Sphere prefix out here where both are in scope.
export type {
	Vec3,
	SphereOpts,
	SpherePlacement,
	Cap,
	Projection,
	TangentFrame,
	FrameOpts
} from './physics/sphere.js';
export {
	orbitIntroPose,
	orbitIntroStart,
	playOrbitIntro,
	orbitConfigFor,
	ORBIT_PRESETS
} from './physics/orbit.js';
export type { CameraPose, OrbitIntroConfig, OrbitPreset } from './physics/orbit.js';

// Flying the camera from orbit down to somebody standing on the surface.
// Public because a cutaway that dives into a figure is a thing consumers
// build — `examples/breach` is the first, and it must reach these by the
// package name rather than by path into `physics/`.
export {
	SURFACE_DISTANCE,
	cameraApproach,
	cameraLerp,
	diveFraming,
	divePose
} from './physics/orbit.js';
export { globeRegistry, registerGlobe, unregisterGlobe } from './physics/globeRegistry.svelte.js';
export type { GlobeHandle } from './physics/globeRegistry.svelte.js';
export { default as GlobeDevControls } from './mesh-studio/globe/GlobeDevControls.svelte';
export { packClusters } from './physics/cluster.js';

// Software-supply-chain walkthrough — a hands-off ~32s kiosk piece built on the
// globe. Its score is authored in source (not the Builder's tour recorder, which
// only persists to localStorage) so a cold visitor plays the whole story.
export {
	ECOSYSTEMS,
	ECOSYSTEM_BY_KEY,
	PACKAGE_GLYPH,
	COMPROMISED_GLYPH,
	PROXY_GLYPH,
	HUB_GLYPH
} from './icons/supply-chain-glyphs.js';
export type { Ecosystem } from './icons/supply-chain-glyphs.js';
export type { ClusterOpts, ClusterPlacement } from './physics/cluster.js';
export type { SunflowerOpts, SunflowerPlacement } from './physics/sunflower.js';
export { packInward, relax } from './physics/solver.js';
export type { Body, Lane, PackOpts, SolveOpts } from './physics/solver.js';

// Shared mesh arrangement options ("Grouped / Packed / Radial / Fan / Globe") +
// the 2D solver behind them, and the picker control that switches between them.
export { MESH_LAYOUTS, solveMeshLayout } from './mesh-studio/layout/mesh-layout.js';
export type {
	MeshLayoutId,
	PlanarMeshLayoutId,
	MeshLayoutOption,
	SolveMeshLayoutOpts,
	Placeable
} from './mesh-studio/layout/mesh-layout.js';
export { default as MeshLayoutPicker } from './mesh-studio/layout/MeshLayoutPicker.svelte';

// The mesh canvas shell (Canvas + globe + placement) and its "View" popover, so a
// consumer hands over logical nodes and gets the same interactive mesh every page
// draws, without owning any geometry.
export { default as MeshCanvas } from './mesh-studio/canvas/MeshCanvas.svelte';
export { default as MeshViewControls } from './mesh-studio/layout/MeshViewControls.svelte';

// A consumer that lays out its own nodes must size them against the same tuning
// MeshStudio renders them with.
export { DEFAULT_TUNING } from './mesh-studio/layout/mesh-tuning.js';
export type { MeshTuning } from './mesh-studio/layout/mesh-tuning.js';
export {
	MESH_NODE_COLOR,
	MESH_NODE_FILL,
	MESH_NODE_LABEL,
	DATA_TYPE_COLOR,
	DATA_TYPE_GLOW
} from './primitives/canvas/canvas.types.js';
export { getPortsForType, portSegments } from './mesh-studio/canvas-ports.js';

// ── Layout ───────────────────────────────────────────────────────────────────
export { default as Modal } from './display/modal/Modal.svelte';
export type { ModalVariant, ModalSize } from './display/modal/Modal.svelte';
export { default as SelectionModal } from './display/modal/SelectionModal.svelte';
export type { SelectionItem } from './display/modal/SelectionModal.svelte';
export { default as IconToolbar } from './layout/IconToolbar.svelte';
export type {
	IconToolbarItem,
	IconToolbarButton,
	IconToolbarMenu,
	IconToolbarOrientation
} from './layout/IconToolbar.svelte';
export { default as Panel } from './primitives/chrome/Panel.svelte';
export type { PanelTone } from './primitives/chrome/Panel.svelte';
export { default as Tooltip } from './primitives/status/Tooltip.svelte';
export type { TooltipPlacement } from './primitives/status/Tooltip.svelte';
export { default as AppShell } from './layout/AppShell.svelte';
export { default as NavDrawer } from './navigation/NavDrawer.svelte';
export { default as Collapsible } from './primitives/chrome/Collapsible.svelte';
export { default as LayoutHeader } from './primitives/chrome/LayoutHeader.svelte';
export { default as PagePanel } from './primitives/chrome/PagePanel.svelte';
export { default as Tabs } from './navigation/Tabs.svelte';
export type { Tab } from './navigation/Tabs.svelte';
export { default as SidebarNav } from './navigation/SidebarNav.svelte';
export type { NavItem, NavSection } from './navigation/SidebarNav.svelte';
export { default as ActionBar } from './primitives/actions/ActionBar.svelte';
export type { ActionBarAction } from './primitives/actions/ActionBar.svelte';
export { default as PageContextMenu } from './primitives/actions/PageContextMenu.svelte';
export type {
	CtxFilterOption,
	CtxFilterGroup,
	CtxSort,
	CtxChip,
	CtxAction
} from './primitives/actions/PageContextMenu.svelte';
export { default as TableWrap } from './display/table/TableWrap.svelte';
export { default as PersonListPanel } from './display/entity/PersonListPanel.svelte';
export type { PersonListItem } from './display/entity/PersonListPanel.svelte';
export { default as SubFooter } from './primitives/chrome/SubFooter.svelte';
export { default as PageHero } from './primitives/cards/PageHero.svelte';
export { default as ClosingCTA } from './primitives/cards/ClosingCTA.svelte';

// ── Navigation ───────────────────────────────────────────────────────────────
export { default as Breadcrumbs } from './navigation/Breadcrumbs.svelte';
export type { BreadcrumbItem } from './navigation/Breadcrumbs.svelte';

// ── Display ──────────────────────────────────────────────────────────────────
export { default as SummaryCards } from './display/metric/SummaryCards.svelte';
export type { SummaryItem, SummaryVariant } from './display/metric/SummaryCards.svelte';
export { default as PanelLoading } from './display/feedback/PanelLoading.svelte';
export { default as DataTable } from './display/table/DataTable.svelte';
export type { KvRow, TableColumn } from './display/table/DataTable.svelte';
export { default as FilterToolbar } from './display/table/FilterToolbar.svelte';
export { default as TablePager, pageWindow } from './display/table/TablePager.svelte';
export { default as BulkActionBar } from './display/table/BulkActionBar.svelte';
export type { BulkAction } from './display/table/BulkActionBar.svelte';
export { default as NodeDrawer } from './display/drawer/NodeDrawer.svelte';
export type { DrawerPosition, TabId as NodeDrawerTabId } from './display/drawer/NodeDrawer.svelte';

// Drawer tab bodies — a summary face, a verdict log and an activity log. Named
// for what they draw rather than for any one host's domain, so the vocabulary
// (an "agent", an "intercept") stays at the call site.
export { default as EntityOverviewTab } from './display/tabs/EntityOverviewTab.svelte';
export type {
	OverviewStat,
	OverviewHighlight,
	OverviewCredential
} from './display/tabs/EntityOverviewTab.svelte';
export { default as OverviewDrawer } from './display/drawer/OverviewDrawer.svelte';
export type { OverviewDrawerStat } from './display/drawer/OverviewDrawer.svelte';
export { default as IncidentDrawer } from './display/drawer/IncidentDrawer.svelte';
export type { IncidentDrawerData } from './display/drawer/IncidentDrawer.svelte';
export { default as SheetDrawer } from './display/drawer/SheetDrawer.svelte';
export type { SheetDrawerSize, SheetDrawerBody } from './display/drawer/SheetDrawer.svelte';
export { default as VerdictLogTab } from './display/tabs/VerdictLogTab.svelte';
export type { VerdictStats, LogFilter, VerdictEntryVM } from './display/tabs/VerdictLogTab.svelte';
export { default as EventLogTab } from './display/tabs/EventLogTab.svelte';
export { eventColor, eventIcon } from './display/tabs/eventLog.js';
export type { LogEventVM, LogEventTone } from './display/tabs/eventLog.js';
export { default as LogRow } from './display/code/LogRow.svelte';
export type { LogLevel } from './display/code/LogRow.svelte';
export { default as AlertBladeHost } from './display/drawer/AlertBladeHost.svelte';
export type { BladePosition } from './display/drawer/AlertBladeHost.svelte';
export { alertBlade } from './display/drawer/alertBlade.svelte.js';
export type {
	AlertBladeItem,
	AlertBladeVariant,
	AlertBladeOptions
} from './display/drawer/alertBlade.svelte.js';
export { default as StatTile } from './display/metric/StatTile.svelte';
export type {
	StatTileSubVariant,
	StatTileHalo,
	StatTileShape
} from './display/metric/StatTile.svelte';
export { default as CountUp } from './display/metric/CountUp.svelte';
export { default as PostureVerdict } from './display/metric/PostureVerdict.svelte';
export type {
	Verdict,
	PostureClause,
	PostureClauseTone
} from './display/metric/PostureVerdict.svelte';
export { default as Sparkline } from './display/metric/Sparkline.svelte';
export { default as PeerCard } from './display/entity/PeerCard.svelte';
export { default as CodeBlock } from './display/code/CodeBlock.svelte';
export { default as ConfigBlock } from './display/code/ConfigBlock.svelte';
export { default as Timeline } from './display/content/Timeline.svelte';
export type { TimelineEvent, TimelineTone, TimelineVariant } from './display/content/Timeline.svelte';
export { default as Avatar } from './display/entity/Avatar.svelte';
export { default as ConsensusBar } from './display/progress/ConsensusBar.svelte';
export { default as TerminalBlock } from './display/code/TerminalBlock.svelte';
export { default as FaqAccordion } from './display/content/FaqAccordion.svelte';
export type { FaqItem } from './display/content/FaqAccordion.svelte';
export { default as HexShield } from './display/feedback/HexShield.svelte';
export { default as ProgressBar } from './display/progress/ProgressBar.svelte';
export type {
	ProgressType,
	ProgressVariant,
	ProgressSize
} from './display/progress/progress.types.js';
export { default as SteppedProgress } from './display/progress/SteppedProgress.svelte';
export type { StepStyle } from './display/progress/SteppedProgress.svelte';
export { default as RadialProgress } from './display/progress/RadialProgress.svelte';
export { default as StackedBar } from './display/progress/StackedBar.svelte';
export type { StackedSegment } from './display/progress/StackedBar.svelte';

// ── Choice lists ─────────────────────────────────────────────────────────────

// Generic form controls. They lived under `assessment/` until the vendor-
// assessment components moved to app-ui; `theme/ThemePicker` uses CheckboxList,
// so these were never domain-specific in the first place.
export { default as SegmentGroup } from './primitives/actions/SegmentGroup.svelte';
export { default as RadioList } from './primitives/forms/RadioList.svelte';
export { default as CheckboxList } from './primitives/forms/CheckboxList.svelte';
export type { ChoiceOption } from './primitives/forms/choice.types.js';

// ── Docs ─────────────────────────────────────────────────────────────────────
export { default as DocsNav } from './docs/DocsNav.svelte';
export type { DocNavGroup, DocNavCard } from './docs/DocsNav.svelte';

// ── Chat ─────────────────────────────────────────────────────────────────────
export { default as ChatMessage } from './display/chat/ChatMessage.svelte';
export type { ChatRole } from './display/chat/ChatMessage.svelte';
export { default as ChatThread } from './display/chat/ChatThread.svelte';
export type { ChatEntry } from './display/chat/ChatThread.svelte';
export { default as Ticker } from './display/metric/Ticker.svelte';
export { default as ProfileCard } from './primitives/cards/ProfileCard.svelte';
export { default as GlowOutline } from './primitives/chrome/GlowOutline.svelte';

// Apply a chrome / emboss / outline / glow / engrave treatment to ANY vector
// art. Reads only the source alpha, so it works on art never authored for it —
// unlike the crests in icons/, whose metal is painted onto their own geometry.
export { default as SvgFx } from './primitives/svg-fx/SvgFx.svelte';
export type { SvgFxType, SvgFxTuning } from './primitives/svg-fx/svg-fx.js';
export {
	FX_DEFAULTS,
	FX_KNOBS,
	FX_BLURB,
	resolveFx,
	fxRegion
} from './primitives/svg-fx/svg-fx.js';

// Layout counterpart: a container whose overlay is allowed to escape it.
export { default as BreakoutStack } from './primitives/chrome/BreakoutStack.svelte';

// ── Builder utilities ────────────────────────────────────────────────────────
export { default as LayerControls } from './builder/LayerControls.svelte';

// ── Chart ────────────────────────────────────────────────────────────────────
export { default as Chart } from './chart/Chart.svelte';
export { default as ChartLegend } from './chart/ChartLegend.svelte';
export { default as DonutChart } from './chart/DonutChart.svelte';
export type { DonutSlice } from './chart/DonutChart.svelte';
export { default as DonutLegend } from './chart/DonutLegend.svelte';
export { default as DonutPopover } from './chart/DonutPopover.svelte';
export type {
	ChartConfig,
	ChartSeries,
	ChartPoint,
	ChartType,
	ChartAnnotation,
	AxisConfig,
	AxisType,
	LegendConfig,
	TooltipConfig,
	ColorFn,
	GradientStop
} from './chart/chart.types.js';
export { CHART_PALETTE, seriesColor } from './chart/chart.types.js';

// ── Theme ────────────────────────────────────────────────────────────────────

// THE RULE: a store is exported from this barrel if and only if a host app needs
// it to drive a component this barrel also exports. Library behaviour is public;
// the state behind showcase's own pages and tools is not.
// 
//   public   theme, advancedSettings, alertBlade, frameControl, frameLatency,
//            perfBudget, globeRegistry — each one is the state behind an
//            exported component (ThemePicker, ActionsMenu, AlertBladeHost,
//            Frame, PerfPanel, GlobeDevControls), and app-ui drives several
//            directly.
//   private  builder (the mockup builder's document), docsLayout (showcase's
//            own DocsShell, which is not exported — app-ui has its own),
//            showcaseState (the doc-page scroll spy).
// 
// `store-exports.spec.ts` enforces this both ways: adding a store without
// exporting it fails, and so does exporting one that belongs to the app.
// Remember that app-ui aliases `showcase` to this source tree, so anything here
// is live API for a second package — see `store-exports.spec.ts` before cutting
// an export that looks unused.
export { default as ThemePicker } from './theme/ThemePicker.svelte';
export { theme } from './theme/store.svelte.js';
export { THEMES, getTheme, resolveChoice } from './theme/themes.js';
export type { Theme, ThemeKey, ThemeChoice, ThemeMode } from './theme/themes.js';

// ── Storyboard ───────────────────────────────────────────────────────────────
export { default as StoryboardCanvas } from './storyboard/StoryboardCanvas.svelte';
export { default as SwimLane } from './storyboard/SwimLane.svelte';
export { default as StoryboardFrame } from './storyboard/StoryboardFrame.svelte';
export { default as StoryboardArrow } from './storyboard/StoryboardArrow.svelte';
export { default as StoryboardBranch } from './storyboard/StoryboardBranch.svelte';

// ── Dev ──────────────────────────────────────────────────────────────────────
export { default as DevCog } from './devcog/DevCog.svelte';
export type { FlagSnapshot } from './devcog/flags/engine.js';
export { createFlagStore } from './devcog/flags/engine.js';
export type { FlagStore, FlagStoreConfig, FlagSource, DevRuntime } from './devcog/flags/engine.js';
export {
	loadNits,
	saveNits,
	parseNits,
	getCssPath,
	buildAIPrompt,
	DEFAULT_NIT_CONFIG
} from './devcog/qa/nits.js';
export type { Nit, NitConfig } from './devcog/qa/nits.js';

// ── ItemFrames (pre-load scaffolds) ──────────────────────────────────────────
export { Frame, FrameDevControls, FrameNumber } from './frames/index.js';
export { FRAME_MAP, FRAME_ATTR, buildFrameCss } from './frames/frames.js';
export { getFrameState } from './frames/context.js';
export { frameControl, frameLatency } from './frames/control.svelte.js';
export type { FrameSpec } from './frames/frames.js';

// ── Motion ───────────────────────────────────────────────────────────────────
export { Flourish } from './motion/index.js';
export { FLOURISHES, normalizeFlourish } from './motion/effects.js';
export type { FlourishKind, FlourishOption } from './motion/effects.js';
export { collapse, collapseCss, readMetrics, COLLAPSE_DURATION } from './motion/collapse.js';
export type { CollapseParams, CollapseMetrics } from './motion/collapse.js';
export { vanish, vanishCss, VANISH_DURATION, VANISH_DEFAULTS } from './motion/vanish.js';
export { prefersReducedMotion } from './motion/reduced-motion.js';
export type { VanishParams, VanishGeometry } from './motion/vanish.js';

// The global catalogue of overlay exit motions — what a primitive resolves
// against instead of hardcoding an animation or taking an `exit` prop.
export { implode, implodeCss, IMPLODE_DURATION, IMPLODE_DEFAULTS } from './motion/implode.js';
export type { ImplodeParams, ImplodeGeometry } from './motion/implode.js';
export { EXITS, EXIT_SPECS, DEFAULT_EXIT, cut, normalizeExit, exitSpec } from './motion/exits.js';
export type { ExitKind, ExitOption, ExitSpec, MotionExit } from './motion/exits.js';

// ── Settings (client-side cache) ─────────────────────────────────────────────
export { advancedSettings } from './settings/store.svelte.js';
export type { AdvancedSettings } from './settings/store.svelte.js';

// ── Perf ─────────────────────────────────────────────────────────────────────
export { perfBudget } from './perf/budget.svelte.js';
export type { PerfTier } from './perf/budget.svelte.js';
export { default as PerfPanel } from './perf/PerfPanel.svelte';
export { frameProbe } from './perf/frame-probe.js';
export type { FrameStats, Quantiles } from './perf/frame-probe.js';

// Lift a live SVG off the page as a file. Written for showcase's own tuning
// controls, but nothing in it is showcase-specific — a consuming app's dev tools
// want the same thing when a canvas state is worth sharing without a screenshot.
export { serializeSvg, downloadSvg, downloadPng, rasterSize } from './dev/svg-export.js';
