// GENERATED by scripts/gen-exports.mjs — do not edit.
//
// The public surface of this package. `app-ui` aliases `showcase` to this
// source tree, so everything below is API for another app.
//
// To change what is exported, edit src/lib/exports.manifest.json and run
// `npm run gen:exports`. Paths are resolved from the filesystem, so moving a
// file between folders needs no edit here or there.

// ── Breakpoints ──────────────────────────────────────────────────────────────
export { BREAKPOINTS } from './breakpoints.js';
export type { BreakpointKey } from './breakpoints.js';
export { useBreakpoint } from './useBreakpoint.svelte.js';

// ── Search ───────────────────────────────────────────────────────────────────
export { fuzzyScore, scoreFields, fuzzyRank } from './fuzzy.js';

// ── Icons ────────────────────────────────────────────────────────────────────
export { default as Icon, ICONS } from './icons/Icon.svelte';
export type { IconName } from './icons/Icon.svelte';

// The brand mark at full fidelity — two-tone, hollowed core, mesh footprint.
// `<Icon name="armornet" />` is the single-weight version for small sizes.
export { default as ArmornetCrest } from './icons/ArmornetCrest.svelte';

// The same crest cut hub-and-spoke, out of the server/node glyph's language.
export { default as ArmornetCrestHub } from './icons/ArmornetCrestHub.svelte';
export { default as ArmornetCrestChrome } from './icons/ArmornetCrestChrome.svelte';

// THE logo. Anything that means "this product" — header, footer, hero,
// favicon — renders this and nothing else. It is ArmornetCrestMesh pinned
// to one shield; that choice lives here so it is made once, not per app.
export { default as ArmornetLogo } from './icons/ArmornetLogo.svelte';

// The crest with the console's own mesh-centre object inside it, cut on seven
// shields. `CREST_MESH_GEOMETRY` is exported so an exporter can read a
// silhouette without instantiating the component.
export { default as ArmornetCrestMesh, CREST_MESH_SHAPES, CREST_MESH_GEOMETRY } from './icons/ArmornetCrestMesh.svelte';
export type { CrestMeshShape } from './icons/ArmornetCrestMesh.svelte';

// Agent-mode node silhouettes — resolve a mode string to its glyph markup
// (defaults to the Terminal glyph when the mode has no assigned outline).
// modeIconName gives the same glyph as an Icon name, for buttons and lists.
export {
	glyphForMode,
	labelForMode,
	TERMINAL_GLYPH,
	modeIconName
} from './icons/mode-tool-icons.js';

// The agent-mode catalog — key, label, desc, colour, glyph, entitlement
// bucket, supported platforms and runtime placement per mode, so a consumer
// can represent every mode the platform runs, not just the ones with live
// agents. Generated from agent/modes.gen.yaml, which `armornet agent modes`
// projects out of the factory registry — each mode declares itself in its
// own Go package via agent.Factory.Describe, so the binary is the source of
// truth, not a hand-kept manifest.
// runtimeEnvsFor/platformsFor return an EMPTY list for an unknown mode, not
// a permissive one: a mode nothing declares must not be offered anywhere.
export {
	MODES,
	MODE_KEYS,
	modeMeta,
	runtimeEnvsFor,
	platformsFor
} from './mesh-studio/modes.gen.js';
export type { ModeMeta, RuntimeEnv, Platform } from './mesh-studio/modes.gen.js';

// ── Brand ────────────────────────────────────────────────────────────────────

// The mark forging itself: the inert line crest spins, ignites, collapses to
// a point and is rebuilt spark by spark into the forged cut. A title scene —
// the breach lobby plays it in front of the setup screen. It owns the clock
// and the composition; every layer below stands on its own.
export { default as LogoForge } from './brand/LogoForge.svelte';

// The same scene with its clock on a scrubber and a jump to each beat. It
// adds nothing to the scene and changes nothing about it — a studio that
// renders a slightly different thing from the shipped one is worse than none.
export { default as LogoForgeStudio } from './brand/LogoForgeStudio.svelte';

// The crest with its figure taken off, so the mesh can turn while the shield
// holds still. Also the one place the two artboards are reconciled: `size`
// means what it means on ArmornetCrestChrome, not what the line crest's own
// 24-unit box would give you.
export { default as ForgeMark } from './brand/ForgeMark.svelte';

// Converging rails and a haze band. A solid needs somewhere to be standing;
// a mark on a flat field is a sticker.
export { default as ForgeFloor } from './brand/ForgeFloor.svelte';

// One lamp, and every surface term read off it — face streak, per-contour
// shading, ball speculars, tube hotspots. Take the lamp away and all of it
// goes dark together, which is what the eye reads as lit.
export { default as RimLight } from './brand/RimLight.svelte';

// Rings off a point, out or in. Time is ms SINCE THE EVENT rather than a
// scene clock, so a scrubbable host gets a scrubbable shock.
export { default as ShockRings } from './brand/ShockRings.svelte';

// Comet trails converging on seats and bursting on contact.
export { default as SparkField } from './brand/SparkField.svelte';

// The timeline and the geometry, exported because the beats are read by
// things that are not the scene: `FORGE_SETTLED` is what a host waits on
// before taking it away, and `markGeometry()` is what a consumer feeds to
// RimLight or ShockRings when it wants one layer without the rest. Both
// builders memoise, and they are separate because the seat plan costs three
// orders of magnitude more than the mark does.
export {
	FORGE,
	FORGE_BEATS,
	FORGE_SETTLED,
	beatAt,
	markGeometry,
	seatPlan
} from './brand/forge.js';
export type { ForgeBeat, MarkGeometry, SeatPlan } from './brand/forge.js';

// The shading maths RimLight renders. Separate from the component so a
// consumer can light contours it cut itself.
export { buildEdges, edgeLight, ballLight, tubeLight } from './brand/rimlight.js';
export type { ContourEdge, Lamp, Band } from './brand/rimlight.js';

// ── Primitives ───────────────────────────────────────────────────────────────
export { default as Button } from './primitives/actions/Button.svelte';
export type {
	ButtonVariant,
	ButtonSize,
	ButtonShape,
	ButtonTone
} from './primitives/actions/Button.svelte';
export { default as IconButton } from './primitives/actions/IconButton.svelte';
export type { IconButtonVariant } from './primitives/actions/IconButton.svelte';
export { default as ActionsMenu } from './primitives/actions/ActionsMenu.svelte';
export { ACTIONS_MENU_DISMISS, resolveDismiss } from './primitives/actions/ActionsMenu.svelte';
export type {
	ActionMenuItem,
	ActionMenuAction,
	ActionMenuHeader,
	ActionMenuSeparator,
	ActionsMenuPlacement,
	ActionsMenuDismiss,
	ActionsMenuDismissConfig,
	ActionsMenuExit
} from './primitives/actions/ActionsMenu.svelte';
export { default as ExportMenu } from './primitives/actions/ExportMenu.svelte';
export type { ExportFormat } from './primitives/actions/ExportMenu.svelte';
export { default as Chip } from './primitives/status/Chip.svelte';
export type { ChipColor, ChipLook } from './primitives/status/Chip.svelte';
export { default as EdgeToolbarCard } from './primitives/cards/EdgeToolbarCard.svelte';
export { default as Tile } from './primitives/chrome/Tile.svelte';
export type { TileVariant } from './primitives/chrome/Tile.svelte';
export { default as StatCard } from './primitives/cards/StatCard.svelte';
export type { StatCardVariant } from './primitives/cards/StatCard.svelte';
export { default as DocCard } from './primitives/cards/DocCard.svelte';
export type { DocCardColor, DocCardStatus, DocCardAuthor } from './primitives/cards/DocCard.svelte';
export { default as HudCard } from './primitives/cards/HudCard.svelte';
export { default as CompositeCard } from './primitives/cards/CompositeCard.svelte';
export type { CompositeCardItem } from './primitives/cards/card.types.js';
export { default as PricingCard } from './primitives/cards/PricingCard.svelte';
export { default as StatusDot } from './primitives/status/StatusDot.svelte';
export { default as StatusBadge } from './primitives/status/StatusBadge.svelte';
export type { StatusLevel } from './primitives/status/StatusDot.svelte';
export { default as Checkbox } from './primitives/forms/Checkbox.svelte';
export { default as Toggle } from './primitives/forms/Toggle.svelte';
export type { ToggleVariant } from './primitives/forms/toggle.types.js';
export { default as Input } from './primitives/forms/Input.svelte';
export type { InputType } from './primitives/forms/Input.svelte';
export { default as PasswordInput } from './primitives/forms/PasswordInput.svelte';
export { default as Textarea } from './primitives/forms/Textarea.svelte';
export { default as FormField } from './primitives/forms/FormField.svelte';
export { default as ChipInput } from './primitives/forms/ChipInput.svelte';
export { default as FileUpload } from './primitives/forms/FileUpload.svelte';
export { default as ViewToggle } from './primitives/actions/ViewToggle.svelte';
export type { ViewToggleOption } from './primitives/actions/ViewToggle.svelte';
export { default as SearchInput } from './primitives/forms/SearchInput.svelte';
export { default as CommandPalette } from './primitives/actions/CommandPalette.svelte';
export type { CmdItem, CmdGroup } from './primitives/actions/CommandPalette.svelte';
export { default as Select } from './primitives/forms/Select.svelte';
export type { SelectOption, SelectOptGroup } from './primitives/forms/Select.svelte';
export { default as SettingRow } from './primitives/forms/SettingRow.svelte';
export { default as UserBlock } from './primitives/cards/UserBlock.svelte';
export { default as StatStrip } from './primitives/chrome/StatStrip.svelte';
export type {
	StatStripItem,
	StatStripColor,
	StatStripDensity
} from './primitives/chrome/StatStrip.svelte';
export { default as EcoTabBar } from './primitives/chrome/EcoTabBar.svelte';
export type { EcoTab } from './primitives/chrome/EcoTabBar.svelte';
export { default as DangerBanner } from './primitives/status/DangerBanner.svelte';
export { default as EmptyState } from './primitives/status/EmptyState.svelte';
export type { EmptyStateVariant } from './primitives/status/EmptyState.svelte';
export { default as SectionBar } from './primitives/chrome/SectionBar.svelte';
export { default as HudCorners } from './primitives/chrome/HudCorners.svelte';
export { default as Canvas } from './primitives/canvas/Canvas.svelte';
export { default as Edge } from './primitives/canvas/Edge.svelte';
export { cssZoom } from './primitives/canvas/css-zoom.js';
export type { EdgeCurve, EdgePoint } from './primitives/canvas/edge-path.js';
export { default as MeshMembrane } from './mesh-studio/membrane/MeshMembrane.svelte';
export type {
	MembraneRegistry,
	MembraneProxy,
	MembraneAgent
} from './mesh-studio/membrane/MeshMembrane.svelte';
export { default as CameraControls } from './primitives/canvas/CameraControls.svelte';
export { default as Minimap } from './primitives/canvas/Minimap.svelte';
export { default as SelectionBox } from './primitives/canvas/SelectionBox.svelte';
export type {
	CanvasCamera,
	TourStep,
	TourController,
	CanvasContextValue,
	SelectionHandler
} from './primitives/canvas/canvas-camera.js';
export type {
	MeshNodeType,
	NodeState,
	DataType,
	EdgeStyle,
	Port
} from './primitives/canvas/canvas.types.js';

// Interactive mesh canvas — radial hub, drag/drop, closest-port line routing.
export { default as MeshStudio } from './mesh-studio/MeshStudio.svelte';
export { default as GlobeFrame } from './mesh-studio/globe/GlobeFrame.svelte';
export { default as TerritoryCaps } from './mesh-studio/globe/TerritoryCaps.svelte';
export type { Territory, TerritoryStyle } from './mesh-studio/globe/TerritoryCaps.svelte';
export { default as NodePiece } from './mesh-studio/pieces/NodePiece.svelte';

// The same solid `NodePiece` draws, with nowhere to stand — a fixed
// head-on frame, so a building can be used as an ICON in a roster or a
// log row and still be the object the canvas draws rather than a flat
// glyph chosen to represent it.
export { default as PieceCrest } from './mesh-studio/pieces/PieceCrest.svelte';
export { default as Backdrop } from './backdrop/Backdrop.svelte';
export { BACKDROPS } from './backdrop/backdrops.js';
export type { BackdropId, BlendMode } from './backdrop/backdrops.js';
export { default as Figure } from './character/Figure.svelte';
export { CHARACTERS, SHAPE_NOTE } from './character/characters.js';
export type { CharacterSkin, Shape } from './character/characters.js';
export { art, figureFacets, DEFAULT_ART } from './character/render.js';
export type { Art, ArtOpts, Tri } from './character/render.js';
export { CLIPS, FRAMES, poseAt, REST } from './character/poses.js';
export type { Clip, ClipId, Pose } from './character/poses.js';
export { STATUSES, lampLevel, statusById } from './character/status.js';
export type { Status, StatusId } from './character/status.js';
export { PIECES, box, gable, tooth, prism, octagon } from './mesh-studio/pieces/pieces.js';
export type { Piece, Solid, PieceVert, PieceId } from './mesh-studio/pieces/pieces.js';
export {
	pieceFacets,
	pieceProjector,
	studioFrame,
	faceViewer,
	band,
	PIECE_LIGHT
} from './mesh-studio/pieces/piece-facets.js';
export type { Facet, FacetOpts } from './mesh-studio/pieces/piece-facets.js';
export { ALL_PIECES, MODE_PIECES, pieceForMode } from './mesh-studio/pieces/piece-catalogue.js';
export { WORKS_PIECES, WORKS_MODE_PIECES } from './mesh-studio/pieces/pieces-works.js';
export { CIVIC_PIECES, CIVIC_MODE_PIECES } from './mesh-studio/pieces/pieces-civic.js';
export type { StudioNode, StudioEdge } from './mesh-studio/studio.types.js';
export { glyphForModes, AGENT_GLYPH } from './icons/mode-tool-icons.js';

// Node sizing + ring placement — a consumer laying out a mesh must size nodes the
// same way MeshStudio draws them, or they overlap.
export {
	packingR,
	silhouetteR,
	labelBox,
	nodeR,
	arcGeom
} from './mesh-studio/layout/mesh-metrics.js';
export type { MetricOpts } from './mesh-studio/layout/mesh-metrics.js';

// Layout physics — pure geometry over circular bodies, with no knowledge of what
// a body stands for. `packRing` seeds a feasible layout; `packInward` draws it in
// around a hub, keeping bodies apart and links legible.
export { packRing, solveRingRadius } from './physics/ring.js';
export type { RingOpts, RingPlacement } from './physics/ring.js';
export { packSunflower, GOLDEN_ANGLE } from './physics/sunflower.js';
export {
	packSphere,
	packSphereClusters,
	solveRadius,
	fibonacciDir,
	capDir,
	capField,
	capRing,
	capRingYaw,
	alignZ,
	spin,
	project,
	projectPoint,
	tangentFrame
} from './physics/sphere.js';

// Ground on a sphere — an elevation field the globe, its nodes and the solids
// standing on them all sample, so they agree about where the surface is.
export {
	makeTerrain,
	terrainLift,
	capMask,
	maskTerrain,
	shapeTerrain,
	contours
} from './physics/terrain.js';
export type {
	Terrain,
	TerrainOpts,
	Relief,
	ContourOpts,
	ContourLine,
	ContourSegment
} from './physics/terrain.js';

// ClusterOpts/ClusterPlacement are declared in both sphere.ts and
// cluster.ts; the barrel has always meant cluster.ts, hence the pin.
export type {
	ClusterOpts as SphereClusterOpts,
	ClusterPlacement as SphereClusterPlacement
} from './physics/cluster.js';

// The sphere's clustering types are named for the same idea as `cluster.ts`'s
// 2D ones, so they carry a Sphere prefix out here where both are in scope.
export type {
	Vec3,
	SphereOpts,
	SpherePlacement,
	Cap,
	Projection,
	TangentFrame,
	FrameOpts
} from './physics/sphere.js';
export {
	orbitIntroPose,
	orbitIntroStart,
	playOrbitIntro,
	orbitConfigFor,
	ORBIT_PRESETS
} from './physics/orbit.js';
export type { CameraPose, OrbitIntroConfig, OrbitPreset } from './physics/orbit.js';

// Flying the camera from orbit down to somebody standing on the surface.
// Public because a cutaway that dives into a figure is a thing consumers
// build — `examples/breach` is the first, and it must reach these by the
// package name rather than by path into `physics/`.
export {
	SURFACE_DISTANCE,
	cameraApproach,
	cameraLerp,
	diveFraming,
	divePose
} from './physics/orbit.js';
export { globeRegistry, registerGlobe, unregisterGlobe } from './physics/globeRegistry.svelte.js';
export type { GlobeHandle } from './physics/globeRegistry.svelte.js';
export { default as GlobeDevControls } from './mesh-studio/globe/GlobeDevControls.svelte';
export { packClusters } from './physics/cluster.js';
export {
	ECOSYSTEMS,
	ECOSYSTEM_BY_KEY,
	PACKAGE_GLYPH,
	COMPROMISED_GLYPH,
	PROXY_GLYPH,
	HUB_GLYPH
} from './icons/supply-chain-glyphs.js';
export type { Ecosystem } from './icons/supply-chain-glyphs.js';
export type { ClusterOpts, ClusterPlacement } from './physics/cluster.js';
export type { SunflowerOpts, SunflowerPlacement } from './physics/sunflower.js';
export { packInward, relax } from './physics/solver.js';
export type { Body, Lane, PackOpts, SolveOpts } from './physics/solver.js';

// Shared mesh arrangement options ("Grouped / Packed / Radial / Fan / Globe") +
// the 2D solver behind them, and the picker control that switches between them.
export { MESH_LAYOUTS, solveMeshLayout } from './mesh-studio/layout/mesh-layout.js';
export type {
	MeshLayoutId,
	PlanarMeshLayoutId,
	MeshLayoutOption,
	SolveMeshLayoutOpts,
	Placeable
} from './mesh-studio/layout/mesh-layout.js';
export { default as MeshLayoutPicker } from './mesh-studio/layout/MeshLayoutPicker.svelte';

// The mesh canvas shell (Canvas + globe + placement) and its "View" popover, so a
// consumer hands over logical nodes and gets the same interactive mesh every page
// draws, without owning any geometry.
export { default as MeshCanvas } from './mesh-studio/canvas/MeshCanvas.svelte';
export { default as MeshViewControls } from './mesh-studio/layout/MeshViewControls.svelte';

// A consumer that lays out its own nodes must size them against the same tuning
// MeshStudio renders them with.
export { DEFAULT_TUNING } from './mesh-studio/layout/mesh-tuning.js';
export type { MeshTuning } from './mesh-studio/layout/mesh-tuning.js';
export {
	MESH_NODE_COLOR,
	MESH_NODE_FILL,
	MESH_NODE_LABEL,
	DATA_TYPE_COLOR,
	DATA_TYPE_GLOW
} from './primitives/canvas/canvas.types.js';
export { getPortsForType, portSegments } from './mesh-studio/canvas-ports.js';

// ── Layout ───────────────────────────────────────────────────────────────────
export { default as Modal } from './display/modal/Modal.svelte';
export type { ModalVariant, ModalSize } from './display/modal/Modal.svelte';
export { default as SelectionModal } from './display/modal/SelectionModal.svelte';
export type { SelectionItem } from './display/modal/SelectionModal.svelte';
export { default as IconToolbar } from './layout/IconToolbar.svelte';
export type {
	IconToolbarItem,
	IconToolbarButton,
	IconToolbarMenu,
	IconToolbarOrientation
} from './layout/IconToolbar.svelte';
export { default as Panel } from './primitives/chrome/Panel.svelte';
export type { PanelTone } from './primitives/chrome/Panel.svelte';
export { default as Tooltip } from './primitives/status/Tooltip.svelte';
export type { TooltipPlacement } from './primitives/status/Tooltip.svelte';
export { default as AppShell } from './layout/AppShell.svelte';
export { default as AuthSplit } from './layout/AuthSplit.svelte';
export { default as NavDrawer } from './navigation/NavDrawer.svelte';
export { default as Collapsible } from './primitives/chrome/Collapsible.svelte';
export { default as LayoutHeader } from './primitives/chrome/LayoutHeader.svelte';
export { default as PagePanel } from './primitives/chrome/PagePanel.svelte';
export { default as Tabs } from './navigation/Tabs.svelte';
export type { Tab } from './navigation/Tabs.svelte';
export { default as SidebarNav } from './navigation/SidebarNav.svelte';
export type { NavItem, NavSection } from './navigation/SidebarNav.svelte';
export { default as ActionBar } from './primitives/actions/ActionBar.svelte';
export type { ActionBarAction } from './primitives/actions/ActionBar.svelte';
export { default as PageContextMenu } from './primitives/actions/PageContextMenu.svelte';
export type {
	CtxFilterOption,
	CtxFilterGroup,
	CtxSort,
	CtxChip,
	CtxAction
} from './primitives/actions/PageContextMenu.svelte';
export { default as TableWrap } from './display/table/TableWrap.svelte';
export { default as PersonListPanel } from './display/entity/PersonListPanel.svelte';
export type { PersonListItem } from './display/entity/PersonListPanel.svelte';
export { default as SubFooter } from './primitives/chrome/SubFooter.svelte';
export { default as PageHero } from './primitives/cards/PageHero.svelte';
export { default as ClosingCTA } from './primitives/cards/ClosingCTA.svelte';

// ── Navigation ───────────────────────────────────────────────────────────────
export { default as Breadcrumbs } from './navigation/Breadcrumbs.svelte';
export type { BreadcrumbItem } from './navigation/Breadcrumbs.svelte';

// ── Display ──────────────────────────────────────────────────────────────────
export { default as SummaryCards } from './display/metric/SummaryCards.svelte';
export type { SummaryItem, SummaryVariant } from './display/metric/SummaryCards.svelte';
export { default as PanelLoading } from './display/feedback/PanelLoading.svelte';
export { default as DataTable } from './display/table/DataTable.svelte';
export type { KvRow, TableColumn } from './display/table/DataTable.svelte';
export { default as FilterToolbar } from './display/table/FilterToolbar.svelte';
export { default as TablePager, pageWindow } from './display/table/TablePager.svelte';
export { default as BulkActionBar } from './display/table/BulkActionBar.svelte';
export type { BulkAction } from './display/table/BulkActionBar.svelte';
export { default as NodeDrawer } from './display/drawer/NodeDrawer.svelte';
export type { DrawerPosition, TabId as NodeDrawerTabId } from './display/drawer/NodeDrawer.svelte';

// Drawer tab bodies — a summary face, a verdict log and an activity log. Named
// for what they draw rather than for any one host's domain, so the vocabulary
// (an "agent", an "intercept") stays at the call site.
export { default as EntityOverviewTab } from './display/tabs/EntityOverviewTab.svelte';
export type {
	OverviewStat,
	OverviewHighlight,
	OverviewCredential
} from './display/tabs/EntityOverviewTab.svelte';
export { default as OverviewDrawer } from './display/drawer/OverviewDrawer.svelte';
export type { OverviewDrawerStat } from './display/drawer/OverviewDrawer.svelte';
export { default as IncidentDrawer } from './display/drawer/IncidentDrawer.svelte';
export type { IncidentDrawerData } from './display/drawer/IncidentDrawer.svelte';
export { default as SheetDrawer } from './display/drawer/SheetDrawer.svelte';
export type { SheetDrawerSize, SheetDrawerBody } from './display/drawer/SheetDrawer.svelte';
export { default as VerdictLogTab } from './display/tabs/VerdictLogTab.svelte';
export type { VerdictStats, LogFilter, VerdictEntryVM } from './display/tabs/VerdictLogTab.svelte';
export { default as EventLogTab } from './display/tabs/EventLogTab.svelte';
export { eventColor, eventIcon } from './display/tabs/eventLog.js';
export type { LogEventVM, LogEventTone } from './display/tabs/eventLog.js';
export { default as LogRow } from './display/code/LogRow.svelte';
export type { LogLevel } from './display/code/LogRow.svelte';
export { default as AlertBladeHost } from './display/drawer/AlertBladeHost.svelte';
export type { BladePosition } from './display/drawer/AlertBladeHost.svelte';
export { alertBlade } from './display/drawer/alertBlade.svelte.js';
export type {
	AlertBladeItem,
	AlertBladeVariant,
	AlertBladeOptions
} from './display/drawer/alertBlade.svelte.js';
export { default as StatTile } from './display/metric/StatTile.svelte';
export type {
	StatTileSubVariant,
	StatTileHalo,
	StatTileShape
} from './display/metric/StatTile.svelte';
export { default as CountUp } from './display/metric/CountUp.svelte';
export { default as PostureVerdict } from './display/metric/PostureVerdict.svelte';
export type {
	Verdict,
	PostureClause,
	PostureClauseTone
} from './display/metric/PostureVerdict.svelte';
export { default as Sparkline } from './display/metric/Sparkline.svelte';
export { default as PeerCard } from './display/entity/PeerCard.svelte';
export { default as CodeBlock } from './display/code/CodeBlock.svelte';
export { default as ConfigBlock } from './display/code/ConfigBlock.svelte';
export { default as Timeline } from './display/content/Timeline.svelte';
export type {
	TimelineEvent,
	TimelineTone,
	TimelineVariant
} from './display/content/Timeline.svelte';
export { default as Avatar } from './display/entity/Avatar.svelte';
export { default as ConsensusBar } from './display/progress/ConsensusBar.svelte';
export { default as TerminalBlock } from './display/code/TerminalBlock.svelte';
export { default as FaqAccordion } from './display/content/FaqAccordion.svelte';
export type { FaqItem } from './display/content/FaqAccordion.svelte';
export { default as CollapsibleStack } from './display/content/CollapsibleStack.svelte';
export { default as CollapsibleStackRow } from './display/content/CollapsibleStackRow.svelte';
export type { CollapsibleStackRowSize } from './display/content/CollapsibleStackRow.svelte';
export type { CollapsibleStackCtx } from './display/content/collapsible-stack.js';
export { default as FileTree } from './display/content/FileTree.svelte';
export type { FileTreeNode } from './display/content/FileTree.svelte';
export { default as HexShield } from './display/feedback/HexShield.svelte';
export { default as ProgressBar } from './display/progress/ProgressBar.svelte';
export type {
	ProgressType,
	ProgressVariant,
	ProgressSize
} from './display/progress/progress.types.js';
export { default as SteppedProgress } from './display/progress/SteppedProgress.svelte';
export type { StepStyle } from './display/progress/SteppedProgress.svelte';
export { default as RadialProgress } from './display/progress/RadialProgress.svelte';
export { default as StackedBar } from './display/progress/StackedBar.svelte';
export type { StackedSegment } from './display/progress/StackedBar.svelte';

// ── Choice lists ─────────────────────────────────────────────────────────────

// Generic form controls. They lived under `assessment/` until the vendor-
// assessment components moved to app-ui; `theme/ThemePicker` uses CheckboxList,
// so these were never domain-specific in the first place.
export { default as SegmentGroup } from './primitives/actions/SegmentGroup.svelte';
export { default as RadioList } from './primitives/forms/RadioList.svelte';
export { default as CheckboxList } from './primitives/forms/CheckboxList.svelte';
export { default as StepSwitcher } from './primitives/forms/StepSwitcher.svelte';
export type { ChoiceOption } from './primitives/forms/choice.types.js';

// ── Docs ─────────────────────────────────────────────────────────────────────
export { default as DocsNav } from './docs/DocsNav.svelte';
export type { DocNavGroup, DocNavCard } from './docs/DocsNav.svelte';
export { default as DocsShell } from './docs/DocsShell.svelte';
export { default as DocsTOC } from './docs/DocsTOC.svelte';
export type { TocHeading } from './docs/DocsTOC.svelte';
export { default as DocsBreadcrumbs } from './docs/DocsBreadcrumbs.svelte';
export { default as DocsMetadata } from './docs/DocsMetadata.svelte';
export type { DocsMeta } from './docs/DocsMetadata.svelte';
export { default as Prose } from './docs/Prose.svelte';

// ── Chat ─────────────────────────────────────────────────────────────────────
export { default as ChatMessage } from './display/chat/ChatMessage.svelte';
export type { ChatRole } from './display/chat/ChatMessage.svelte';
export { default as ChatThread } from './display/chat/ChatThread.svelte';
export type { ChatEntry } from './display/chat/ChatThread.svelte';
export { default as Ticker } from './display/metric/Ticker.svelte';
export { default as ProfileCard } from './primitives/cards/ProfileCard.svelte';
export { default as GlowOutline } from './primitives/chrome/GlowOutline.svelte';

// Apply a chrome / emboss / outline / glow / engrave treatment to ANY vector
// art. Reads only the source alpha, so it works on art never authored for it —
// unlike the crests in icons/, whose metal is painted onto their own geometry.
export { default as SvgFx } from './primitives/svg-fx/SvgFx.svelte';
export type { SvgFxType, SvgFxTuning } from './primitives/svg-fx/svg-fx.js';
export {
	FX_DEFAULTS,
	FX_KNOBS,
	FX_BLURB,
	resolveFx,
	fxRegion
} from './primitives/svg-fx/svg-fx.js';

// Layout counterpart: a container whose overlay is allowed to escape it.
export { default as BreakoutStack } from './primitives/chrome/BreakoutStack.svelte';

// ── Builder utilities ────────────────────────────────────────────────────────
export { default as LayerControls } from './builder/LayerControls.svelte';

// What a piece of an app-ui page IS, for the builder-template capture.
// app-ui declares its regions in typed source; the generator imports
// them rather than reading props back out of the DOM.
export { defineRegions } from './builder/template-spec.js';
export type { TemplateRegion, TemplateRegions } from './builder/template-spec.js';

// ── Chart ────────────────────────────────────────────────────────────────────
export { default as Chart } from './chart/Chart.svelte';
export { default as ChartLegend } from './chart/ChartLegend.svelte';
export { default as DonutChart } from './chart/DonutChart.svelte';
export type { DonutSlice } from './chart/DonutChart.svelte';
export { default as DonutLegend } from './chart/DonutLegend.svelte';
export { default as DonutPopover } from './chart/DonutPopover.svelte';
export type {
	ChartConfig,
	ChartSeries,
	ChartPoint,
	ChartType,
	ChartAnnotation,
	AxisConfig,
	AxisType,
	LegendConfig,
	TooltipConfig,
	ColorFn,
	GradientStop,
	GaugeConfig,
	GaugeBand
} from './chart/chart.types.js';
export { CHART_PALETTE, seriesColor } from './chart/chart.types.js';

// ── Theme ────────────────────────────────────────────────────────────────────

// THE RULE: a store is exported from this barrel if and only if a host app needs
// it to drive a component this barrel also exports. Library behaviour is public;
// the state behind showcase's own pages and tools is not.
// 
//   public   theme, advancedSettings, alertBlade, frameControl, frameLatency,
//            perfBudget, globeRegistry — each one is the state behind an
//            exported component (ThemePicker, ActionsMenu, AlertBladeHost,
//            Frame, PerfPanel, GlobeDevControls), and app-ui drives several
//            directly.
//   private  builder (the mockup builder's document), docsLayout (showcase's
//            own DocsShell, which is not exported — app-ui has its own),
//            showcaseState (the doc-page scroll spy).
// 
// `store-exports.spec.ts` enforces this both ways: adding a store without
// exporting it fails, and so does exporting one that belongs to the app.
// Remember that app-ui aliases `showcase` to this source tree, so anything here
// is live API for a second package — see `store-exports.spec.ts` before cutting
// an export that looks unused.
export { default as ThemePicker } from './theme/ThemePicker.svelte';
export { default as AppearanceCard } from './theme/AppearanceCard.svelte';
export { theme } from './theme/store.svelte.js';
export { appearance } from './theme/appearance.svelte.js';
export type { AppearanceMode } from './theme/appearance.svelte.js';
export { THEMES, getTheme, resolveChoice } from './theme/themes.js';
export type { Theme, ThemeKey, ThemeChoice, ThemeMode } from './theme/themes.js';

// ── Storyboard ───────────────────────────────────────────────────────────────
export { default as StoryboardCanvas } from './storyboard/StoryboardCanvas.svelte';
export { default as SwimLane } from './storyboard/SwimLane.svelte';
export { default as StoryboardFrame } from './storyboard/StoryboardFrame.svelte';
export { default as StoryboardArrow } from './storyboard/StoryboardArrow.svelte';
export { default as StoryboardBranch } from './storyboard/StoryboardBranch.svelte';

// ── Dev ──────────────────────────────────────────────────────────────────────
export { default as DevCog } from './devcog/DevCog.svelte';
export type { FlagSnapshot } from './devcog/flags/engine.js';
export { createFlagStore } from './devcog/flags/engine.js';
export type { FlagStore, FlagStoreConfig, FlagSource, DevRuntime } from './devcog/flags/engine.js';
export {
	loadNits,
	saveNits,
	parseNits,
	getCssPath,
	buildAIPrompt,
	DEFAULT_NIT_CONFIG
} from './devcog/qa/nits.js';
export type { Nit, NitConfig } from './devcog/qa/nits.js';

// ── ItemFrames (pre-load scaffolds) ──────────────────────────────────────────
export { Frame, FrameDevControls, FrameNumber } from './frames/index.js';
export { FRAME_MAP, FRAME_ATTR, buildFrameCss } from './frames/frames.js';
export { getFrameState } from './frames/context.js';
export { frameControl, frameLatency } from './frames/control.svelte.js';
export type { FrameSpec } from './frames/frames.js';

// ── Motion ───────────────────────────────────────────────────────────────────
export { Flourish } from './motion/index.js';
export { FLOURISHES, normalizeFlourish } from './motion/effects.js';
export type { FlourishKind, FlourishOption } from './motion/effects.js';
export { collapse, collapseCss, readMetrics, COLLAPSE_DURATION } from './motion/collapse.js';
export type { CollapseParams, CollapseMetrics } from './motion/collapse.js';
export { vanish, vanishCss, VANISH_DURATION, VANISH_DEFAULTS } from './motion/vanish.js';
export { prefersReducedMotion } from './motion/reduced-motion.js';
export type { VanishParams, VanishGeometry } from './motion/vanish.js';

// The global catalogue of overlay exit motions — what a primitive resolves
// against instead of hardcoding an animation or taking an `exit` prop.
export { implode, implodeCss, IMPLODE_DURATION, IMPLODE_DEFAULTS } from './motion/implode.js';
export type { ImplodeParams, ImplodeGeometry } from './motion/implode.js';
export { EXITS, EXIT_SPECS, DEFAULT_EXIT, cut, normalizeExit, exitSpec } from './motion/exits.js';
export type { ExitKind, ExitOption, ExitSpec, MotionExit } from './motion/exits.js';

// ── Settings (client-side cache) ─────────────────────────────────────────────
export { advancedSettings } from './settings/store.svelte.js';
export type { AdvancedSettings } from './settings/store.svelte.js';

// The cog's panel, also mounted on its own by app-ui's onboarding step.
export { default as AdvancedSettingsPanel } from './settings/AdvancedSettingsPanel.svelte';

// ── Perf ─────────────────────────────────────────────────────────────────────
export { perfBudget } from './perf/budget.svelte.js';
export type { PerfTier } from './perf/budget.svelte.js';
export { default as PerfPanel } from './perf/PerfPanel.svelte';
export { frameProbe } from './perf/frame-probe.js';
export type { FrameStats, Quantiles } from './perf/frame-probe.js';

// Lift a live SVG off the page as a file. Written for showcase's own tuning
// controls, but nothing in it is showcase-specific — a consuming app's dev tools
// want the same thing when a canvas state is worth sharing without a screenshot.
export { serializeSvg, downloadSvg, downloadPng, rasterSize } from './dev/svg-export.js';

// ── Model Explorer ───────────────────────────────────────────────────────────

// The database schema as a pannable diagram: grouped table cards, routed FK
// edges, a searchable table list and an inspector. ErdLayer, ErdTableList,
// ErdInspector and ErdToolbar are its internals and stay unexported — the
// diagram owns its own layout and selection state, and a consumer that
// assembled the parts by hand would be reimplementing that.
export { default as ErdDiagram } from './model-explorer/ErdDiagram.svelte';
export { default as ErdOverviewView } from './model-explorer/ErdOverviewView.svelte';
export { default as ErdLedgerView } from './model-explorer/ErdLedgerView.svelte';
export { default as ErdCompareView } from './model-explorer/ErdCompareView.svelte';
export { default as ErdEnvironmentsView } from './model-explorer/ErdEnvironmentsView.svelte';
export { default as ErdCapturesView } from './model-explorer/ErdCapturesView.svelte';

// Wire types, matching the Go `json:` tags in dbmgr exactly. They are shared
// rather than redeclared per consumer so a schema-manager front end — dbmgr's
// own embedded console today — parses the same shapes the server emits.
export {
	defaultErdData,
	defaultErdDiff,
	defaultDriftReport,
	defaultEnvironmentsReport
} from './model-explorer/types.js';
export type {
	Erd,
	ErdData,
	ErdTable,
	ErdColumn,
	ErdIndex,
	ErdCheck,
	ErdForeignKey,
	ErdGroup,
	MigrationEvent,
	LedgerEntry,
	ChangeClass,
	ObjectDiff,
	ErdDiff,
	DriftReport,
	CaptureMeta,
	EnvSummary,
	EnvMatrixRow,
	EnvironmentsReport
} from './model-explorer/types.js';

// ── Browser agent (WASM Agent Line) ──────────────────────────────────────────
// The WebAssembly Agent Line client every armornet agent runs, compiled for the
// browser, plus the registry that shares its ONE connection out per capability.
// Public because two apps speak over it — the breach example here and the
// live-assessment client in app-ui — and a second registry would put two
// subscribers back on one socket, which is the bug this replaced.

// `loadWasmModule` is public because the transport is no longer the only Go
// module in the page — the breach rules engine is a second one, and it needs
// the same once-per-URL memoised load rather than a private copy of it.
export { loadAgent, loadWasmModule } from './agent/loader.js';
export type { ArmornetAgent } from './agent/types.js';

// No capability constant is exported: a capability name belongs with the client
// that speaks it, and a shared registry that listed them would be enumerating
// its own consumers.
export {
	declareCapability,
	subscribeCapability,
	unsubscribeCapability,
	capabilityHolder,
	decodeAgentPayload
} from './agent/registry.js';
export type { LostCause } from './agent/registry.js';
