// Code generated by cmd/appgen from apps.yaml. DO NOT EDIT.

/*
 * Every URL prefix, asset namespace, dev port and build directory below is
 * written ONCE, in apps.yaml. Editing this file instead means the next
 * generator run silently reverts you — and the drift check will fail the
 * build before that, which is the point.
 * 
 * Import APP_BASE from a svelte.config.js or vite.config.ts to set the app's
 * base path. The dev proxy is generated from the same manifest entry, so the
 * baked-in prefix and the prefix that routes to it cannot disagree.
 */

/** Each app's base path, as its build config must set it. An app mounted at
 *  the root has NO base — SvelteKit rejects '/' and wants '' instead, which
 *  is the sort of detail that belongs in a generator and not in five
 *  config files. */
export const APP_BASE = {
	console: '',
	showcase: '/showcase',
	breach: '/breach',
	jobboard: '',
	installer: '',
};

/** Where each toolchain writes its bundle, relative to the app's source.
 *  SvelteKit's adapter-static writes build/; a plain Vite build writes
 *  dist/. The embed pipeline copies from here. */
export const APP_BUILD_DIR = {
	console: 'build',
	showcase: 'build',
	breach: 'dist',
	jobboard: 'build',
	installer: 'dist',
};

/** Each app's private asset namespace, derived from its NAME. */
export const APP_ASSETS = {
	console: '/_apps/console',
	showcase: '/_apps/showcase',
	breach: '/_apps/breach',
	jobboard: '/_apps/jobboard',
	installer: '/_apps/installer',
};
