// Code generated by cmd/modegen from agent/modes.gen.yaml. DO NOT EDIT.
//
// That file is itself generated, by `armornet agent modes -o yaml`, from the
// factory registry — each mode is declared by its own agent package, via
// agent.Factory.Describe. Edit that factory and run `make generate`.

/** Where an agent runs, as opposed to what it does. */
export type RuntimeEnv = 'browser' | 'cloud' | 'local';

/** A platform a mode declares it runs on: a released GOOS, or wasm. */
export type Platform = 'darwin' | 'linux' | 'wasm' | 'windows';

/** Every mode key the catalog declares.
 *
 *  Use it for tables that must cover every mode. Do NOT use it for a value
 *  that came off the wire or out of the database — `modeMeta` takes a plain
 *  string on purpose, because a stored record can outlive its mode. */
export type ModeKey = 'browser' | 'codebase_analysis' | 'dns_proxy' | 'fetch' | 'github_runner' | 'hardened_agent' | 'harness' | 'hello_world' | 'intelligence' | 'language' | 'momus' | 'posture' | 'supply_chain_proxy' | 'vendor_management' | 'vscode_enforcement';

/** One agent mode's UI metadata. Glyph SVGs are NOT here — they are
 *  hand-authored in icons/mode-tool-icons.ts and looked up by key. */
export interface ModeMeta {
	key: ModeKey;
	label: string;
	desc: string;
	about: string;
	color: string;
	/** Option name in MODE_GLYPHS for this mode; '' when none is drawn yet. */
	glyph: string;
	/** Entitlement pool this mode draws from. 'other' is 0 on the free tier. */
	bucket: 'github' | 'language' | 'proxy' | 'notify' | 'other';
	/** Tool types this mode's agent requires but does not construct itself. */
	tools: string[];
	/** Operating systems this mode can run on. */
	platforms: Platform[];
	/** Where this mode may be placed. */
	runtimeEnvs: RuntimeEnv[];
	/** False when the mode is declared but the build has no factory for it —
	 *  it can be shown, but it cannot be deployed. */
	registered: boolean;
}

export const MODES: ModeMeta[] = [
	{ key: 'hello_world', label: 'Hello World', desc: 'demo / onboarding agent', about: '', color: '#C4A8FF', glyph: 'Terminal', bucket: 'other', tools: [], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local', 'cloud'], registered: true },
	{ key: 'fetch', label: 'Fetch', desc: 'retrieves one URL and answers with the body', about: '', color: '#60A5FA', glyph: '', bucket: 'other', tools: ['httprequest'], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local', 'cloud'], registered: true },
	{ key: 'intelligence', label: 'Intelligence', desc: 'discovering threats', about: '', color: '#22D3EE', glyph: 'Console', bucket: 'other', tools: [], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['cloud'], registered: true },
	{ key: 'vendor_management', label: 'Third Party', desc: 'third-party vendor risk', about: 'Judges the suppliers in your inventory. Reads the Armory\'s recent threat events and scan results to decide whether a vendor presents a current supply-chain risk, and feeds the trust profile you share with customers. It assesses what is already on your list — adding to that list is still a human job.', color: '#FB923C', glyph: 'Buildings', bucket: 'other', tools: [], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local', 'cloud'], registered: true },
	{ key: 'codebase_analysis', label: 'Codebase Analysis', desc: 'static codebase understanding — ecosystems & proxy recommendations', about: 'Clones a repository and works out which package ecosystems it uses, then emits a Supply Chain proxy config you can paste straight into agent.yaml. Its product is an enforcement recommendation, not a finding — it tells you which relays to stand up. Hardened Agent is the one that scans what those dependencies actually contain.', color: '#34D399', glyph: 'Source scan', bucket: 'github', tools: [], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local', 'cloud'], registered: true },
	{ key: 'github_runner', label: 'GitHub Runner', desc: 'secure build environment', about: '', color: '#6EE7B7', glyph: 'Vault', bucket: 'other', tools: [], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local', 'cloud'], registered: true },
	{ key: 'hardened_agent', label: 'Hardened Agent', desc: 'isolated sandbox agent for untrusted work', about: 'Runs dependency scanning inside an isolated sandbox, so untrusted package code never touches your estate. A four-pass pipeline — SBOM, AST, install trace, then an LLM read — writes what it found to dep_scan_results, which Vendor Risk uses to judge a supplier. The sandbox is HOW it works, not what it produces: the output is a dependency verdict, not a block.', color: '#F87171', glyph: 'Contained', bucket: 'other', tools: [], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local', 'cloud'], registered: true },
	{ key: 'supply_chain_proxy', label: 'Supply Chain', desc: 'package registry proxy / scan', about: '', color: '#38BDF8', glyph: 'Guarded pkg', bucket: 'proxy', tools: [], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local', 'cloud'], registered: true },
	{ key: 'dns_proxy', label: 'DNS Proxy', desc: 'DNS filtering / sinkhole', about: '', color: '#60A5FA', glyph: 'Block domain', bucket: 'proxy', tools: ['dnsproxy'], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local'], registered: true },
	{ key: 'language', label: 'Language', desc: 'LLM reasoning jury / blades', about: '', color: '#FBBF24', glyph: 'Verdict', bucket: 'language', tools: [], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local', 'cloud'], registered: true },
	{ key: 'harness', label: 'Harness', desc: 'conversational agent — text exchange over the mesh', about: '', color: '#F59E0B', glyph: 'Exchange line', bucket: 'other', tools: [], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local', 'cloud'], registered: true },
	{ key: 'momus', label: 'Momus', desc: 'watches your security program and tells you when something needs you', about: 'The agent that makes sure you find out. Everything else here produces findings, expiries and failures; Momus is what turns them into a message in the place you actually look — Slack, email, a ticket. It claims alert jobs the server queues and reports whether each one landed, so a notification that never arrived is itself visible rather than silent. Run one and your program can reach you; run none and it can only wait to be checked on.', color: '#E879F9', glyph: 'Dispatch', bucket: 'notify', tools: [], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local', 'cloud'], registered: true },
	{ key: 'browser', label: 'Browser', desc: 'WebAssembly agent hosted by a page', about: '', color: '#7DD3FC', glyph: '', bucket: 'other', tools: [], platforms: ['wasm'], runtimeEnvs: ['browser'], registered: true },
	{ key: 'vscode_enforcement', label: 'Editor Policy', desc: 'VS Code / Cursor policy enforcement', about: '', color: '#818CF8', glyph: 'Editor policy', bucket: 'other', tools: ['vscodepolicy', 'vscodeinv'], platforms: ['darwin', 'linux', 'windows'], runtimeEnvs: ['local'], registered: true },
	{ key: 'posture', label: 'Posture', desc: 'security-posture checks (cluster CIS benchmark, …)', about: '', color: '#38BDF8', glyph: 'Gauge', bucket: 'other', tools: [], platforms: ['linux'], runtimeEnvs: ['local'], registered: true },
];

export const MODE_KEYS: ModeKey[] = MODES.map((m) => m.key);

const BY_KEY = new Map<string, ModeMeta>(MODES.map((m) => [m.key, m]));

/** The catalog entry for a wire value, or undefined for a mode this build
 *  does not know — a stored record can outlive the mode that wrote it. */
export function modeMeta(key: string): ModeMeta | undefined {
	return BY_KEY.get(key);
}

/** Where a mode may run. Unknown modes get an EMPTY list, not a permissive
 *  one: a mode nothing declares must not be offered anywhere. */
export function runtimeEnvsFor(key: string): RuntimeEnv[] {
	return BY_KEY.get(key)?.runtimeEnvs ?? [];
}

/** Operating systems a mode supports. Empty for an unknown mode, same reason. */
export function platformsFor(key: string): Platform[] {
	return BY_KEY.get(key)?.platforms ?? [];
}
