// Code generated by cmd/modegen from agent/modes.yaml. DO NOT EDIT.

/** One agent mode's UI metadata. Glyph SVGs are NOT here — they are
 *  hand-authored in icons/mode-tool-icons.ts and looked up by key. */
export interface ModeMeta {
	key: string;
	label: string;
	desc: string;
	color: string;
	/** Option name in MODE_GLYPHS for this mode; '' when none is drawn yet. */
	glyph: string;
	/** Entitlement pool this mode draws from. 'other' is 0 on the free tier. */
	bucket: 'github' | 'language' | 'proxy' | 'notify' | 'other';
}

export const MODES: ModeMeta[] = [
	{ key: 'hello_world', label: 'Hello World', desc: 'demo / onboarding agent', color: '#C4A8FF', glyph: 'Terminal', bucket: 'other' },
	{ key: 'intelligence', label: 'Intelligence', desc: 'discovering threats', color: '#22D3EE', glyph: 'Console', bucket: 'other' },
	{ key: 'vendor_management', label: 'Vendor Risk', desc: 'third-party vendor risk', color: '#FB923C', glyph: 'Buildings', bucket: 'other' },
	{ key: 'dep_analysis', label: 'Dep Analysis', desc: 'dependency tree scanning', color: '#4ADE80', glyph: '', bucket: 'other' },
	{ key: 'codebase_analysis', label: 'Codebase Analysis', desc: 'static codebase understanding — ecosystems & proxy recommendations', color: '#34D399', glyph: '', bucket: 'github' },
	{ key: 'github_runner', label: 'GitHub Runner', desc: 'secure build environment', color: '#6EE7B7', glyph: 'Vault', bucket: 'other' },
	{ key: 'hardened_agent', label: 'Hardened Agent', desc: 'isolated sandbox agent for untrusted work', color: '#F87171', glyph: '', bucket: 'other' },
	{ key: 'supply_chain_proxy', label: 'Supply Chain', desc: 'package registry proxy / scan', color: '#38BDF8', glyph: 'Guarded pkg', bucket: 'proxy' },
	{ key: 'dns_proxy', label: 'DNS Proxy', desc: 'DNS filtering / sinkhole', color: '#60A5FA', glyph: 'Block domain', bucket: 'proxy' },
	{ key: 'language', label: 'Language', desc: 'LLM reasoning jury / blades', color: '#FBBF24', glyph: 'Verdict', bucket: 'language' },
	{ key: 'harness', label: 'Harness', desc: 'conversational agent — text exchange over the mesh', color: '#F59E0B', glyph: '', bucket: 'other' },
	{ key: 'momus', label: 'Momus', desc: 'notification agent — claims alert jobs and delivers them outbound', color: '#E879F9', glyph: '', bucket: 'notify' },
	{ key: 'feed_content_analysis', label: 'Feed Analysis', desc: 'threat feed content analysis', color: '#A78BFA', glyph: '', bucket: 'other' },
	{ key: 'vendor_identification', label: 'Vendor ID', desc: 'vendor discovery / identification', color: '#F472B6', glyph: '', bucket: 'other' },
	{ key: 'control_plane_management', label: 'Control Plane', desc: 'control plane management', color: '#94A3B8', glyph: '', bucket: 'other' },
	{ key: 'vscode_enforcement', label: 'Editor Policy', desc: 'VS Code / Cursor policy enforcement', color: '#818CF8', glyph: '', bucket: 'other' },
	{ key: 'posture', label: 'Posture', desc: 'security-posture checks (cluster CIS benchmark, …)', color: '#38BDF8', glyph: '', bucket: 'other' },
];

export const MODE_KEYS: string[] = MODES.map((m) => m.key);
