// GENERATED by armornet's scripts/gen-templates.mjs — DO NOT EDIT.
//
// Every template below was measured off a live render of the app-ui page named
// beside it: the coordinates are the layout the browser actually performed, not
// a guess at it. Re-run `make generate-templates` after changing one of those
// pages, or the template will keep describing the screen as it used to be.
//
// The generator lives in armornet rather than here because this is a nested
// repository — see scripts/gen-templates.mjs there for how a page becomes a
// template. Hand-written templates belong in templates.ts, which concatenates
// both lists.
//
// Captured pages:
//   app-login                  /login (2 items)
//   app-pricing                /pricing (1 items)
//   app-overview               /overview (3 items)
//   app-vendor-list            /vendor (7 items)
//   app-risk-register          /risk/register (9 items)
//   app-exposure               /exposure (10 items)
//   app-org-users              /console/org/users (2 items)

import type { BuilderTemplate } from './templates.js';

export const GENERATED_TEMPLATES: BuilderTemplate[] = [
	{
		id: "app-login",
		name: "Sign-in screen",
		description: "The real login screen — connectors, fields and submit.",
		frame: { preset: "desktop-1440", name: "Sign in" },
		items: [
			{ componentId: "Input", x: 0, y: 0, w: 340, h: 40, props: { placeholder: "your-workspace" } },
			{ componentId: "Button", x: 0, y: 60, props: { size: "lg", __children: "Continue" } }
		]
	},
	{
		id: "app-pricing",
		name: "Pricing page",
		description: "Marketing pricing tiers as they ship.",
		frame: { preset: "desktop-1440", name: "Pricing" },
		items: [
			{ componentId: "FaqAccordion", x: 0, y: 0, w: 1080, h: 380 }
		]
	},
	{
		id: "app-overview",
		name: "Console overview",
		description: "The landing console screen — stats, charts and activity.",
		frame: { preset: "desktop-1440", name: "Overview" },
		items: [
			{ componentId: "RadialProgress", x: 0, y: 0 },
			{ componentId: "Timeline", x: 0, y: 420, w: 260, h: 540 },
			{ componentId: "Chart", x: 880, y: 40, w: 280, h: 80 }
		]
	},
	{
		id: "app-vendor-list",
		name: "Vendor list",
		description: "Vendor inventory — filters over a records table.",
		frame: { preset: "desktop-1440", name: "Vendors" },
		items: [
			{ componentId: "LayoutHeader", x: 0, y: 0, w: 1220, h: 40, props: { eyebrow: "// third party · vendors" } },
			{ componentId: "PostureVerdict", x: 20, y: 80 },
			{ componentId: "CountUp", x: 340, y: 80 },
			{ componentId: "Panel", x: 20, y: 200, w: 1180, h: 200 },
			{ componentId: "RadialProgress", x: 40, y: 260 },
			{ componentId: "Panel", x: 20, y: 420, w: 580, h: 420 },
			{ componentId: "Panel", x: 620, y: 420, w: 580, h: 420, props: { __children: "Assessment Activity No recent assessment activity" } }
		]
	},
	{
		id: "app-risk-register",
		name: "Risk register",
		description: "The risk register table and its header controls.",
		frame: { preset: "desktop-1440", name: "Risk register" },
		items: [
			{ componentId: "LayoutHeader", x: 0, y: 0, w: 1220, h: 240, props: { eyebrow: "// risk management · register" } },
			{ componentId: "StatStrip", x: 20, y: 260, w: 1180, h: 40 },
			{ componentId: "DataTable", x: 20, y: 340, w: 1180, h: 460 },
			{ componentId: "Avatar", x: 760, y: 400 },
			{ componentId: "Avatar", x: 760, y: 460 },
			{ componentId: "Avatar", x: 760, y: 540 },
			{ componentId: "Avatar", x: 760, y: 600 },
			{ componentId: "Avatar", x: 760, y: 680 },
			{ componentId: "Avatar", x: 760, y: 740 }
		]
	},
	{
		id: "app-exposure",
		name: "Relay exposure",
		description: "Exposure surface — interception summary over a detail table.",
		frame: { preset: "desktop-1440", name: "Exposure" },
		items: [
			{ componentId: "LayoutHeader", x: 0, y: 0, w: 1220, h: 40, props: { eyebrow: "// risk management · exposure" } },
			{ componentId: "StatStrip", x: 40, y: 80, w: 1120, h: 60 },
			{ componentId: "Panel", x: 40, y: 160, w: 1120 },
			{ componentId: "Panel", x: 40, y: 340, w: 680, h: 460 },
			{ componentId: "Chart", x: 60, y: 400, w: 660, h: 360 },
			{ componentId: "Panel", x: 760, y: 340, w: 420, h: 460 },
			{ componentId: "Panel", x: 40, y: 820, w: 480, h: 320 },
			{ componentId: "DonutChart", x: 60, y: 880 },
			{ componentId: "Chart", x: 180, y: 880, w: 180, h: 180 },
			{ componentId: "Panel", x: 540, y: 820, w: 620, h: 320 }
		]
	},
	{
		id: "app-org-users",
		name: "Org users",
		description: "Settings screen — section bar over a membership table.",
		frame: { preset: "desktop-1440", name: "Users" },
		items: [
			{ componentId: "LayoutHeader", x: 0, y: 0, w: 1220, h: 180, props: { eyebrow: "// admin · user management" } },
			{ componentId: "DataTable", x: 20, y: 260, w: 1180, h: 280, props: { variant: "table", columns: "[{\"key\":\"user\",\"header\":\"User ID\"},{\"key\":\"role\",\"header\":\"Role\"},{\"key\":\"since\",\"header\":\"Member since\"}]", tableRows: "[{\"user\":\"google|dana\",\"role\":\"owner\",\"since\":\"3/4/2024\"},{\"user\":\"google|sam\",\"role\":\"admin\",\"since\":\"8/19/2024\"},{\"user\":\"google|ali\",\"role\":\"member\",\"since\":\"1/27/2025\"},{\"user\":\"okta|jules\",\"role\":\"member\",\"since\":\"6/11/2025\"}]" } }
		]
	}
];

/** The app-ui page each template was measured from, for the palette's tooltip. */
export const GENERATED_SOURCES: Record<string, string> = {
	"app-login": "/login",
	"app-pricing": "/pricing",
	"app-overview": "/overview",
	"app-vendor-list": "/vendor",
	"app-risk-register": "/risk/register",
	"app-exposure": "/exposure",
	"app-org-users": "/console/org/users"
};
