// ── /examples/breach · the rules ──────────────────────────────────────────
// BREACH is a 2v2 tabletop skirmish played on the armornet globe. One side runs
// a supply-chain intrusion; the other runs the estate it is aimed at. The board
// is the same four-territory sphere the console's overview draws, so a player
// who learns this map has learned where a real compromise happens.
//
// ── This file used to BE the rules. It is now a thin layer over them ─────────
// The board, the roster, the deck and the upgrade tracks were ~450 lines of
// hand-authored literals here, and ~450 more in Go, and nothing checked one
// against the other. They agreed until somebody rebalanced a card, and then the
// client lit a target the server refused.
//
// They now come from `rules.gen.ts`, generated by `cmd/breachgen` out of the
// canonical `internal/breach/{rules,cards}.yaml`. Re-exported from here so that
// every component keeps importing what it always imported — the data moved, the
// module boundary did not.
//
// ── What is still authored here, and why ────────────────────────────────────
// The pure functions the standalone demo INTERPRETS the generated data with:
// the outcome bands, the 2d6 distribution, the odds arithmetic, the ownership
// test. They are the same rules the Go engine applies, and they are duplicated
// on purpose and only for the no-backend demo — `showcase` is a component
// library and an example that needs a Go server and a database to open is an
// example nobody opens.
//
// The safety property that makes that duplication acceptable: they can only
// ever run when there is no authority to disagree with. `BreachMatch.perform`
// refuses to resolve anything once `remote` is set, so on a real table these
// functions price the HUD and decide nothing. See the note there.
//
// If you are adding a rule: it goes in `internal/breach` first. It comes here
// only if the offline demo cannot work without it.

import type { CharacterSkin } from 'showcase';
import {
	INITIATIVE,
	ROSTER as GEN_ROSTER,
	type Ability,
	type Faction,
	type Klass as GenKlass,
	type Outcome,
	type Owner,
	type Structure
} from './rules.gen.js';

// ── The generated half ───────────────────────────────────────────────────────
// Data only. Regenerate with `make breachgen` after editing the canonical YAML.
export {
	CHAIN,
	CORE_ID,
	GARRISON_CAP,
	HORIZON,
	INITIATIVE,
	SKILL_BLURB,
	SKILL_LABEL,
	STRUCTURES,
	TERRITORIES,
	TERRITORY_ORDER,
	UPGRADE_ROUNDS,
	abilitiesOf,
	abilityByKey,
	cardByKey,
	catalogueFor,
	powerOf,
	structureById,
	trackFor,
	unlockedFor,
	CATALOGUE,
	UPGRADES
} from './rules.gen.js';

export type {
	Ability,
	Power,
	AbilityKind,
	CardDef,
	Faction,
	Outcome,
	Owner,
	Passive,
	Skill,
	Structure,
	TerritoryDef,
	TerritoryKey,
	Upgrade,
	UpgradeKind
} from './rules.gen.js';

/**
 * A seat, as the renderer needs it.
 *
 * The generated `Klass` types `shape` as a plain string, because Go has no
 * union type to carry the four silhouettes and the engine never reads the
 * field. The renderer does, and `CharacterSkin` is how it says so — so the
 * widening happens exactly here, once, rather than at every draw site.
 */
export type Klass = Omit<GenKlass, 'shape'> & CharacterSkin;

export const ROSTER: Klass[] = GEN_ROSTER as Klass[];

export const klassByKey = (k: string): Klass => ROSTER.find((r) => r.key === k) ?? ROSTER[0];

// The re-export block above is `export ... from`, which puts nothing in local
// scope — so the generated pieces this file BUILDS ON have to be imported as
// well as forwarded.
import { abilityByKey as abilityByKeyGen } from './rules.gen.js';
import type { Power as PowerDef } from './rules.gen.js';

/**
 * The four signature powers — one per class, and the closest thing the deck has
 * to a protagonist's move.
 *
 * Worth naming because they are a CATEGORY the generated accessors do not
 * expose. `CATALOGUE` is the cards a side can hold and `abilitiesOf` reads out
 * of it; a signature lives on the klass instead, so every list-shaped question
 * about "all the playable moves" silently answers four short.
 *
 * The property that makes this set useful elsewhere: every one is `uses: 1`.
 * A signature is burned once a game by the one class that has it, which means
 * anything hung off this list is rare BY THE RULES rather than by somebody
 * remembering to be sparing.
 */
export const SIGNATURES: Array<{ klass: Klass; power: PowerDef }> = ROSTER.flatMap((k) =>
	k.power ? [{ klass: k, power: k.power }] : []
);

export const isSignature = (key: string): boolean =>
	SIGNATURES.some((s) => s.power.key === key);

/**
 * The display name of any playable card, wherever the generator put it.
 *
 * `abilityByKey` only searches `CATALOGUE`, so it structurally cannot find the
 * four klass SIGNATURE powers — Zero-Day Reserve among them, which is the
 * loudest card in the game. Anything starting from a card KEY rather than from
 * a seat wants both lists, and the failure is quiet in the worst way: the
 * lookup returns undefined and the caller renders a slug.
 *
 * Here rather than in `rules.gen.ts` because that file is generated from the Go
 * rules and an accessor added to it does not survive the next regeneration.
 */
export const cardNameFor = (key: string): string =>
	abilityByKeyGen(key)?.name ?? ROSTER.find((k) => k.power?.key === key)?.power?.name ?? key;

// ── Outcome ──────────────────────────────────────────────────────────────────
// How well it went — the dice say degree, not just yes or no.
//
// The number printed on the card is what a CLEAN roll gets you. Everything else
// is measured against that, which means one table covers every card in the game
// and a player only ever has to learn it once.
//
//   botch     −5 or worse. It goes wrong in a way that costs you something.
//   fail      short of the mark, including an exact tie — ties go to the defender.
//   partial   just over. Half the printed effect, rounded up.
//   clean     +4 or better. Exactly what the card says.
//   critical  +8 or better. The card, and then some.

export const OUTCOME_LABEL: Record<Outcome, string> = {
	botch: 'BOTCHED',
	fail: 'FAILED',
	partial: 'PARTIAL',
	clean: 'CLEAN',
	critical: 'CRITICAL'
};

export const OUTCOME_COLOR: Record<Outcome, string> = {
	botch: '#EF4444',
	fail: '#94A3B8',
	partial: '#FBBF24',
	clean: '#34D399',
	critical: '#7DD3FC'
};

export const outcomeFor = (margin: number): Outcome =>
	margin <= -5
		? 'botch'
		: margin <= 0
			? 'fail'
			: margin <= 3
				? 'partial'
				: margin <= 7
					? 'clean'
					: 'critical';

export const succeeded = (o: Outcome) => o === 'partial' || o === 'clean' || o === 'critical';

/** The printed number, scaled by how well the roll went. */
export function scaleEffect(o: Outcome, base: number): number {
	if (!succeeded(o)) return 0;
	if (o === 'partial') return Math.max(1, Math.ceil(base / 2));
	if (o === 'critical') return base + 1;
	return base;
}

// ── Where a card may be played ───────────────────────────────────────────────

/**
 * The default is the obvious one and it is worth stating: you may act on ground
 * the other side owns, and on the neutral supply chain both sides live off. You
 * may NOT act on your own — attacking your own registry is not a move, and
 * hardening the enemy's relay is not either.
 *
 * `ability.on` overrides it, which is how blue gets a counter-offensive: a card
 * naming `['red']` reaches into the staging grounds, and that is the only way
 * the defenders ever get to be the ones arriving somewhere.
 */
export function canTarget(a: Ability, s: Structure, actor: Faction): boolean {
	if (a.targets && !a.targets.includes(s.id)) return false;
	const allowed: Owner[] = a.on ?? ['neutral', actor === 'red' ? 'blue' : 'red'];
	// Blue's estate-tending cards (harden, quarantine, rebuild) are the exception
	// the default cannot express: they act on blue's OWN ground.
	return allowed.includes(s.owner);
}

// ── Table size ───────────────────────────────────────────────────────────────

/**
 * How many chairs are in play.
 *
 * These two, and no more. A bigger table would need characters to put in it,
 * and the roster is four — `BENCH` is flavour, its entries have no skills, no
 * passive and no abilities, so they cannot be dealt to a seat. Offering `3v3`
 * would be offering a setting that cannot reach a rule.
 */
export type MatchSize = '1v1' | '2v2';

export const MATCH_SIZES: Array<{ id: MatchSize; label: string; blurb: string }> = [
	{
		id: '2v2',
		label: '2v2',
		blurb: 'Four chairs. You have an ally, and you act either side of an enemy.'
	},
	{
		id: '1v1',
		label: '1v1',
		blurb: 'Two chairs. No ally, no cover — every mistake on your side is yours.'
	}
];

/** The chairs in play at a given size, as klass keys in initiative order.
 *  One seat per side at 1v1, taking the first of each — so the order alternates
 *  at every size and `phase` keeps meaning the same thing. */
export function seatOrder(size: MatchSize): string[] {
	if (size === '1v1') {
		const first = (f: Faction) => INITIATIVE.find((k) => klassByKey(k).faction === f)!;
		return [first('red'), first('blue')];
	}
	return [...INITIATIVE];
}

/** Classes drawn but not seated in this match — the rest of the box. */
export const BENCH = [
	{ name: 'Access Broker', faction: 'red' as Faction, note: 'Buys footholds nobody had to earn.' },
	{ name: 'Hacktivist', faction: 'red' as Faction, note: 'Loud on purpose. Heat is the objective.' },
	{
		name: 'Incident Commander',
		faction: 'blue' as Faction,
		note: 'Contains fast, understands later.'
	},
	{ name: 'Auditor', faction: 'blue' as Faction, note: 'Turns evidence into a control that holds.' }
];

// ── Resolution ───────────────────────────────────────────────────────────────
// 2d6 + modifiers against the building's hardening. Ties go to the defender —
// an attack that only just works did not work. A margin of 4 or better plants a
// PERSISTENT foothold, which survives the first eviction: this is why real
// intrusions are cheap to start and expensive to remove.

const TWO_D6_COUNTS = [0, 0, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1];

/** Probability that 2d6 lands at or above `n`. */
export function oddsAtLeast(n: number): number {
	if (n <= 2) return 1;
	if (n > 12) return 0;
	let c = 0;
	for (let s = n; s <= 12; s++) c += TWO_D6_COUNTS[s];
	return c / 36;
}

// ── Dice ─────────────────────────────────────────────────────────────────────
// The throw is a seam rather than a call to `Math.random`, for the same reason
// Go's `Rand` is one (internal/breach/errors.go): the dice decide the game, so a
// test has to be able to say what they landed on. A rules test that can only
// assert "something happened" is not a rules test.

/** Where a throw gets its numbers. `intN` returns a value in [0, n), which is
 *  the shape Go's `Rand` has — so one script of values pins both engines. */
export interface DiceSource {
	intN(n: number): number;
}

/** What a real table rolls with. */
export const DICE: DiceSource = { intN: (n) => Math.floor(Math.random() * n) };

/** Replays a script of values, then repeats its last one forever. The TS half of
 *  Go's `FixedRand`, down to the clamping, so a golden vector written against
 *  one engine reads the same in the other. */
export function fixedDice(values: number[]): DiceSource {
	let at = 0;
	return {
		intN: (n) => {
			if (n <= 0 || !values.length) return 0;
			return Math.abs(values[Math.min(at++, values.length - 1)]) % n;
		}
	};
}

/** A throw nobody ruled on, agreed between browsers.
 *
 *  The faces swatted out of the air at a seal decide nothing, so the server
 *  never sends them — but two players sitting next to each other watching
 *  different numbers get swatted read it as the dice being out of sync. Seeded
 *  off the resolution's seq, which every client at the table already has. */
export function seededDice(seed: number): DiceSource {
	let s = (seed * 2654435761) >>> 0 || 1;
	return {
		intN: (n) => {
			// xorshift32 — the point is that it is the SAME sequence everywhere,
			// not that it is a good generator.
			s ^= s << 13;
			s ^= s >>> 17;
			s ^= s << 5;
			s >>>= 0;
			return n <= 0 ? 0 : s % n;
		}
	};
}

export function roll2d6(src: DiceSource = DICE): { dice: [number, number]; total: number } {
	const a = 1 + src.intN(6);
	const b = 1 + src.intN(6);
	return { dice: [a, b], total: a + b };
}

export interface Odds {
	/** Everything the actor adds to the dice, itemised — the HUD shows the parts
	 *  because "+7" tells a player nothing about which of their choices earned it. */
	skill: number;
	abilityMod: number;
	resourceMod: number;
	/** What the ground you already hold is worth on this roll — see `leverage`. */
	holdMod: number;
	modifier: number;
	/** The number to beat: a building's live hardening, or the card's own DC. */
	target: number;
	/** What the dice alone must reach for each band. Ties go to the defender, so
	 *  the first success is at target + 1. */
	needed: number;
	neededClean: number;
	/** Probability of at least a partial, and of at least a clean. */
	chance: number;
	chanceClean: number;
	/** Chance the roll goes badly enough to cost you something. */
	chanceBotch: number;
}

export function computeOdds(opts: {
	/** The building's hardening, when a building is defending. */
	hardening?: number;
	/** The card's own difficulty, when nothing is. */
	dc?: number;
	skill: number;
	abilityMod: number;
	resourceMod: number;
	holdMod?: number;
	defenceMod: number;
}): Odds {
	const hold = opts.holdMod ?? 0;
	const modifier = opts.skill + opts.abilityMod + opts.resourceMod + hold;
	const target = (opts.hardening ?? opts.dc ?? 8) + opts.defenceMod;
	const needed = target - modifier + 1;
	const neededClean = target - modifier + 4;
	// A botch is margin ≤ −5, i.e. the dice landing at or below target − 5 − mod.
	const botchAtMost = target - modifier - 5;
	return {
		skill: opts.skill,
		abilityMod: opts.abilityMod,
		resourceMod: opts.resourceMod,
		holdMod: hold,
		modifier,
		target,
		needed,
		neededClean,
		chance: oddsAtLeast(needed),
		chanceClean: oddsAtLeast(neededClean),
		chanceBotch: 1 - oddsAtLeast(botchAtMost + 1)
	};
}

/** Heat → what the meter is called depends on which chair you are in. */
export const meterName = (f: Faction) => (f === 'red' ? 'HEAT' : 'DETECTION');
