// Code generated by cmd/breachgen from internal/breach/{rules,cards}.yaml.
// DO NOT EDIT — your change will be overwritten by the next `make breachgen`.
//
// This is the printed rulebook: what the board is, who the characters are, and
// what every card costs and says. It is data, and it is the SAME data the Go
// engine resolves against, which is the entire point of generating it.
//
// What is not here, and never will be: the decision procedure. Nothing in this
// file rolls dice, resolves an attack or decides what a seat may see. Those
// live in internal/breach on the server. The standalone demo interprets the
// data below; it does not carry a second ruleset.

export type Faction = 'red' | 'blue';
export type Owner = Faction | 'neutral';
export type TerritoryKey = 'commons' | 'foundry' | 'marches' | 'outlands' | 'staging';
export type Skill = 'social' | 'tech' | 'opsec' | 'analysis';
export type AbilityKind = 'strike' | 'implant' | 'recon' | 'control' | 'econ' | 'utility';
export type Outcome = 'botch' | 'fail' | 'partial' | 'clean' | 'critical';
export type UpgradeKind = 'roll' | 'ap' | 'quiet' | 'harden';

export interface TerritoryDef {
	key: TerritoryKey;
	name: string;
	real: string;
	color: string;
	glow: string;
	biome: string;
	blurb: string;
	owner: Owner;
}

export interface Structure {
	id: string;
	name: string;
	role: string;
	territory: TerritoryKey;
	owner: Owner;
	piece: string;
	/** The number an attack roll has to beat before anything modifies it. */
	hardening: number;
	/** Blue's standing defences. Shown, not added — already priced into hardening. */
	controls: string[];
	/** 1-based position on the payload path; absent when off the chain. */
	chain?: number;
	note: string;
}

export interface Passive {
	name: string;
	text: string;
}

export interface Klass {
	key: string;
	seat: string;
	name: string;
	faction: Faction;
	color: string;
	icon: string;
	/** The silhouette the renderer draws. No rule reads it. */
	shape: string;
	resource: string;
	skills: Record<Skill, number>;
	tagline: string;
	passive: Passive;
	/** This character's own move. Absent for a class that has none. */
	power?: Power;
}

export interface Upgrade {
	key: string;
	/** The round it comes online. Unlocked, never bought. */
	at: number;
	kind: UpgradeKind;
	value: number;
	name: string;
	icon: string;
	text: string;
}

export interface Ability {
	key: string;
	name: string;
	kind: AbilityKind;
	skill: Skill;
	/** Action points. */
	ap: number;
	/** Roll bonus the card itself brings. */
	mod: number;
	/** Heat added to the target's territory. Failure multiplies it. */
	noise: number;
	/** What the roll is measured against when no building defends. */
	dc?: number;
	targets?: string[];
	on?: Owner[];
	text: string;
}

/**
 * A character's own move.
 *
 * Priced and rolled exactly like a card, and never in a deck — so it cannot be
 * shuffled away from the one person it belongs to. The four of these used to be
 * signature cards, and the discard pile broke that promise.
 */
export interface Power extends Ability {
	/** Charges it starts a match with. Spent, then bought back. */
	uses: number;
}

export interface CardDef {
	ability: Ability;
	/** The klass that contributes it — this decides the card's side. */
	owner: string;
	side: Faction;
	copies: number;
}

/** The last round. Blue survives to it; red has until it to hold the path. */
export const HORIZON = 12;

/** Most figures of one side that fit on a building. */
export const GARRISON_CAP = 5;

/** The protected core at the centre of the globe. */
export const CORE_ID = 'core';

/** Rounds the three upgrade slots come online. Same for every seat. */
export const UPGRADE_ROUNDS = [3, 6, 9] as const;

/** The regions, in board order. */
export const TERRITORY_ORDER: TerritoryKey[] = [
	'staging',
	'outlands',
	'commons',
	'foundry',
	'marches',
];

export const TERRITORIES: Record<TerritoryKey, TerritoryDef> = {
	staging: {
		key: 'staging',
		name: 'The Staging Grounds',
		real: 'Adversary infrastructure',
		color: '#F472B6',
		glow: '#FBCFE8',
		biome: 'scattered',
		blurb: 'Rented, disposable and somewhere else. Everything red owns is here.',
		owner: 'red'
	},
	outlands: {
		key: 'outlands',
		name: 'The Outlands',
		real: 'Third parties & upstream',
		color: '#FB923C',
		glow: '#FDBA74',
		biome: 'scattered',
		blurb: 'Islands both sides depend on and neither owns. The siege starts here.',
		owner: 'neutral'
	},
	commons: {
		key: 'commons',
		name: 'The Commons',
		real: 'Source & development',
		color: '#34D399',
		glow: '#6EE7B7',
		biome: 'rolling',
		blurb: 'Open ground. Anyone may walk in and offer you a patch.',
		owner: 'blue'
	},
	foundry: {
		key: 'foundry',
		name: 'The Foundry',
		real: 'Build & registry',
		color: '#38BDF8',
		glow: '#7DD3FC',
		biome: 'terraced',
		blurb: 'Where source becomes an artifact — and stops being readable.',
		owner: 'blue'
	},
	marches: {
		key: 'marches',
		name: 'The Marches',
		real: 'Runtime & network',
		color: '#818CF8',
		glow: '#A5B4FC',
		biome: 'ridged',
		blurb: 'The high, watched ground between the estate and the world.',
		owner: 'blue'
	},
};

export const STRUCTURES: Structure[] = [
	{
		id: 'beacon',
		name: 'Relay Beacon',
		role: 'Command & control',
		territory: 'staging',
		owner: 'red',
		piece: 'beacon',
		hardening: 9,
		controls: ['fast flux', 'domain rotation'],
		note: 'Every implant calls home to this. Cut it and the things red has planted go dark — and visible.'
	},
	{
		id: 'workshop',
		name: 'Exploit Workshop',
		role: 'Capability development',
		territory: 'staging',
		owner: 'red',
		piece: 'factory',
		hardening: 11,
		controls: ['air gap'],
		note: 'Where the zero-day is kept until it is worth spending. Burn it down and it cannot be spent at all.'
	},
	{
		id: 'personas',
		name: 'Persona Farm',
		role: 'Identity manufacture',
		territory: 'staging',
		owner: 'red',
		piece: 'hut',
		hardening: 7,
		controls: [],
		note: 'Two years of plausible commit history, grown from nothing. The Maintainer came out of here.'
	},
	{
		id: 'forum',
		name: 'Maintainer Circle',
		role: 'Upstream project',
		territory: 'outlands',
		owner: 'neutral',
		piece: 'forum',
		hardening: 8,
		controls: ['two-person review'],
		chain: 1,
		note: 'One exhausted volunteer, two years of unanswered issues, and a very helpful newcomer.'
	},
	{
		id: 'mark',
		name: 'Vendor Market',
		role: 'Third-party registry',
		territory: 'outlands',
		owner: 'neutral',
		piece: 'mark',
		hardening: 10,
		controls: ['vendor assessment'],
		note: 'Everyone you buy from, standing in one square, priced by how much they can hurt you.'
	},
	{
		id: 'observatory',
		name: 'The Observatory',
		role: 'Threat intelligence',
		territory: 'outlands',
		owner: 'neutral',
		piece: 'observatory',
		hardening: 11,
		controls: ['feed ingest', 'IOC match'],
		note: 'Sees far, and always a little late. Blue may spend a turn here to look at any region.'
	},
	{
		id: 'house',
		name: 'Package Mirror',
		role: 'Dependency mirror',
		territory: 'outlands',
		owner: 'neutral',
		piece: 'house',
		hardening: 9,
		controls: ['checksum pin'],
		note: 'A copy of the world, kept close for speed. Poison the copy, skip the world.'
	},
	{
		id: 'archive',
		name: 'The Archive',
		role: 'Source repository',
		territory: 'commons',
		owner: 'blue',
		piece: 'archive',
		hardening: 11,
		controls: ['branch protection', 'CODEOWNERS'],
		chain: 2,
		note: 'Everything here is readable by everyone. That is the defence, and it is thinner than it sounds.'
	},
	{
		id: 'precinct',
		name: 'Developer Precinct',
		role: 'Engineer endpoints',
		territory: 'commons',
		owner: 'blue',
		piece: 'precinct',
		hardening: 10,
		controls: ['extension policy'],
		note: 'Forty laptops, each one a door into the Commons with a person holding it open.'
	},
	{
		id: 'hut',
		name: 'Contributor Sandbox',
		role: 'Untrusted workspace',
		territory: 'commons',
		owner: 'blue',
		piece: 'hut',
		hardening: 6,
		controls: [],
		note: 'Deliberately cheap. Red is meant to take this one — it is what taking it BUYS that matters.'
	},
	{
		id: 'forge',
		name: 'The Forge',
		role: 'Build runner (CI)',
		territory: 'foundry',
		owner: 'blue',
		piece: 'forge',
		hardening: 12,
		controls: ['ephemeral runners', 'egress policy'],
		chain: 3,
		note: 'Runs whatever the build script says, with credentials, on a machine nobody watches.'
	},
	{
		id: 'silos',
		name: 'The Silos',
		role: 'Artifact registry',
		territory: 'foundry',
		owner: 'blue',
		piece: 'silos',
		hardening: 12,
		controls: ['signing'],
		chain: 4,
		note: 'What ships lives here — and what ships is not always what was written.'
	},
	{
		id: 'mill',
		name: 'Dependency Mill',
		role: 'Build cache',
		territory: 'foundry',
		owner: 'blue',
		piece: 'mill',
		hardening: 8,
		controls: [],
		note: 'Grinds thousands of upstream packages into your build. Nobody reads the grain.'
	},
	{
		id: 'court',
		name: 'Attestation Court',
		role: 'Provenance & signing',
		territory: 'foundry',
		owner: 'blue',
		piece: 'court',
		hardening: 13,
		controls: ['SLSA provenance', 'key custody'],
		note: 'The only building that can testify that an artifact came from the source it claims.'
	},
	{
		id: 'checkpoint',
		name: 'The Checkpoint',
		role: 'Egress & DNS relay',
		territory: 'marches',
		owner: 'blue',
		piece: 'checkpoint',
		hardening: 13,
		controls: ['DNS policy', 'relay interception'],
		chain: 5,
		note: 'The last gate before the world. A payload that cannot call home is a payload that failed.'
	},
	{
		id: 'keep',
		name: 'The Keep',
		role: 'Control plane',
		territory: 'marches',
		owner: 'blue',
		piece: 'keep',
		hardening: 15,
		controls: ['mTLS', 'break-glass audit'],
		note: 'Take the Keep and you do not need the chain. Which is why it is priced like that.'
	},
	{
		id: 'bastion',
		name: 'Posture Bastion',
		role: 'Configuration posture',
		territory: 'marches',
		owner: 'blue',
		piece: 'bastion',
		hardening: 11,
		controls: ['CIS baseline'],
		note: 'Holds the standard everything else is measured against. Bend it and the map lies to Blue.'
	},
	{
		id: 'redoubt',
		name: 'Hardened Runtime',
		role: 'Production workload',
		territory: 'marches',
		owner: 'blue',
		piece: 'redoubt',
		hardening: 14,
		controls: ['sandboxing', 'read-only rootfs'],
		note: 'The prize. Red does not attack it — Red arrives inside it, carried by something you trust.'
	},
];

/** The payload path. The first four may be taken in any order; the payload
 * requires all four of them. Position drives leverage, not legality. */
export const CHAIN: Structure[] = STRUCTURES.filter((s) => s.chain).sort(
	(a, b) => (a.chain ?? 0) - (b.chain ?? 0)
);

export const structureById = (id: string): Structure | undefined =>
	STRUCTURES.find((s) => s.id === id);

export const SKILL_LABEL: Record<Skill, string> = {
	social: 'SOCIAL',
	tech: 'TECH',
	opsec: 'OPSEC',
	analysis: 'ANALYSIS',
};

export const SKILL_BLURB: Record<Skill, string> = {
	social: 'Persuasion, personas, and being the helpful one for two years.',
	tech: 'Exploits, builds, and knowing what the code actually does.',
	opsec: 'Not being seen doing any of it.',
	analysis: 'Looking at a thing long enough to notice it is wrong.',
};

export const ROSTER: Klass[] = [
	{
		key: 'maintainer',
		seat: 'R1',
		name: 'The Maintainer',
		faction: 'red',
		color: '#F472B6',
		icon: 'user',
		shape: 'runner',
		resource: 'REP',
		skills: { social: 3, tech: 1, opsec: 1, analysis: 0 },
		tagline: 'Patient, helpful, and eventually holding the keys.',
		passive: { name: 'Trust Accrual', text: 'End a round having taken no loud action and gain 2 REP. Spend REP 1-for-1 as a roll bonus — nobody audits a friend.' },
		power: {
			key: 'fixture',
			name: 'Obfuscated Test Fixture',
			kind: 'implant',
			skill: 'tech',
			ap: 2,
			mod: 3,
			noise: 1,
			targets: ['archive', 'hut', 'forum'],
			text: 'The payload ships as corrupt binary test data. Review reads diffs, and this has no diff worth reading.',
			uses: 1
		}
	},
	{
		key: 'state',
		seat: 'R2',
		name: 'The Handler',
		faction: 'red',
		color: '#FB923C',
		icon: 'radar',
		shape: 'ghost',
		resource: 'BANK',
		skills: { social: -1, tech: 3, opsec: 3, analysis: 1 },
		tagline: 'A state has no deadline. You do.',
		passive: { name: 'Patience', text: 'Unspent AP banks, to a maximum of 6. A zero-day loses no value sitting in a drawer for a year.' },
		power: {
			key: 'zeroday',
			name: 'Zero-Day Reserve',
			kind: 'strike',
			skill: 'tech',
			ap: 3,
			mod: 6,
			noise: 3,
			text: 'Burn it. It works once, it is loud once, and afterwards it is a signature everyone has.',
			uses: 1
		}
	},
	{
		key: 'architect',
		seat: 'B1',
		name: 'The Architect',
		faction: 'blue',
		color: '#38BDF8',
		icon: 'shapes',
		shape: 'brute',
		resource: 'BUDGET',
		skills: { social: 0, tech: 3, opsec: 1, analysis: 2 },
		tagline: 'Cannot see the attacker. Can make the ground refuse to carry them.',
		passive: { name: 'Reproducible Builds', text: 'While you hold at least 1 AP, the Forge and the Silos each stand at +2 hardening. Determinism is a wall.' },
		power: {
			key: 'segment',
			name: 'Segment',
			kind: 'control',
			skill: 'tech',
			ap: 2,
			mod: 0,
			noise: 0,
			dc: 9,
			on: ['red', 'blue', 'neutral'],
			text: 'Cut a lane for 2 rounds. Nothing crosses it — including everything of yours that used it. Played on the Relay Beacon it sinkholes the callback, and every implant red is running goes dark.',
			uses: 1
		}
	},
	{
		key: 'hunter',
		seat: 'B2',
		name: 'The Threat Hunter',
		faction: 'blue',
		color: '#34D399',
		icon: 'radar',
		shape: 'drone',
		resource: 'SIGNAL',
		skills: { social: 0, tech: 1, opsec: 1, analysis: 4 },
		tagline: 'Assumes the breach already happened and goes looking for it.',
		passive: { name: 'Baseline', text: 'One free sweep each round in the territory you stand in. You know what normal looks like here.' },
		power: {
			key: 'attribute',
			name: 'Attribution',
			kind: 'utility',
			skill: 'social',
			ap: 3,
			mod: 0,
			noise: 0,
			dc: 11,
			on: ['red'],
			text: 'Name the actor while a revealed foothold stands. Played on the Persona Farm it burns the identity: the account, the history and the trust go with it.',
			uses: 1
		}
	},
];

/** The order the chairs act in: red, blue, red, blue. */
export const INITIATIVE: string[] = [
	'maintainer',
	'architect',
	'state',
	'hunter',
];

export const klassByKey = (key: string): Klass =>
	ROSTER.find((r) => r.key === key) ?? ROSTER[0];

export const UPGRADES: Record<string, Upgrade[]> = {
	maintainer: [
		{
			key: 'reviewer',
			at: 3,
			kind: 'roll',
			value: 1,
			name: 'Trusted Reviewer',
			icon: 'check-circle',
			text: 'Two years of good patches. +1 on everything you attempt.'
		},
		{
			key: 'commit',
			at: 6,
			kind: 'quiet',
			value: 2,
			name: 'Commit Rights',
			icon: 'key',
			text: 'You are supposed to be in here now. Your actions make 2 less heat.'
		},
		{
			key: 'release',
			at: 9,
			kind: 'roll',
			value: 2,
			name: 'Release Manager',
			icon: 'package',
			text: 'You sign the tarball. +2 more on everything you attempt.'
		},
	],
	state: [
		{
			key: 'infra',
			at: 3,
			kind: 'quiet',
			value: 3,
			name: 'Clean Infrastructure',
			icon: 'eye-off',
			text: 'Nothing points back. Your actions make 3 less heat.'
		},
		{
			key: 'cover',
			at: 6,
			kind: 'roll',
			value: 2,
			name: 'Deep Cover',
			icon: 'snowflake',
			text: 'Patience is a capability. +2 on everything you attempt.'
		},
		{
			key: 'burst',
			at: 9,
			kind: 'ap',
			value: 1,
			name: 'Burst Capacity',
			icon: 'cpu',
			text: 'The budget finally lands. +1 action point a round.'
		},
	],
	architect: [
		{
			key: 'baseline',
			at: 3,
			kind: 'harden',
			value: 1,
			name: 'Hardened Baseline',
			icon: 'shield',
			text: 'Every building on your side stands 1 higher.'
		},
		{
			key: 'reproducible',
			at: 6,
			kind: 'harden',
			value: 2,
			name: 'Reproducible Builds',
			icon: 'git-merge',
			text: 'Determinism is a wall. 2 more on top of that.'
		},
		{
			key: 'immutable',
			at: 9,
			kind: 'ap',
			value: 1,
			name: 'Immutable Releases',
			icon: 'lock',
			text: 'Nothing ships unreviewed. +1 action point a round.'
		},
	],
	hunter: [
		{
			key: 'net',
			at: 3,
			kind: 'roll',
			value: 1,
			name: 'Wide Net',
			icon: 'radar',
			text: 'More sensors, more coverage. +1 on everything you attempt.'
		},
		{
			key: 'behaviour',
			at: 6,
			kind: 'ap',
			value: 1,
			name: 'Behavioural Baseline',
			icon: 'activity',
			text: 'You know what normal looks like. +1 action point a round.'
		},
		{
			key: 'attribution',
			at: 9,
			kind: 'harden',
			value: 2,
			name: 'Attribution Engine',
			icon: 'fingerprint',
			text: 'Naming them is a defence. Your side stands 2 higher.'
		},
	],
};

export const trackFor = (klassKey: string): Upgrade[] => UPGRADES[klassKey] ?? [];

/** The upgrades online for a seat at a given round. */
export const unlockedFor = (klassKey: string, round: number): Upgrade[] =>
	trackFor(klassKey).filter((u) => round >= u.at);

export const CATALOGUE: CardDef[] = [
	{
		ability: {
			key: 'contribution',
			name: 'Earnest Contribution',
			kind: 'econ',
			skill: 'social',
			ap: 1,
			mod: 0,
			noise: 0,
			dc: 6,
			text: 'Fix real bugs for real people. +3 REP, no heat. This is the majority of the attack and it is not an attack.',
		},
		owner: 'maintainer',
		side: 'red',
		copies: 3
	},
	{
		ability: {
			key: 'pressure',
			name: 'Co-maintainer Pressure',
			kind: 'control',
			skill: 'social',
			ap: 1,
			mod: 0,
			noise: 1,
			dc: 8,
			text: 'Sock-puppets complain the project is unmaintained until the owner shares commit rights. Target −3 hardening for 2 rounds.',
		},
		owner: 'maintainer',
		side: 'red',
		copies: 2
	},
	{
		ability: {
			key: 'divergence',
			name: 'Release Divergence',
			kind: 'strike',
			skill: 'tech',
			ap: 2,
			mod: 4,
			noise: 2,
			targets: ['forge', 'silos'],
			text: 'The build script in the release tarball is not the one in the repo. Only an artifact-to-source diff can see it.',
		},
		owner: 'maintainer',
		side: 'red',
		copies: 2
	},
	{
		ability: {
			key: 'lotl',
			name: 'Living off the Land',
			kind: 'strike',
			skill: 'opsec',
			ap: 2,
			mod: 1,
			noise: 0,
			text: 'Every tool used is one the estate installed itself. Nothing to detect, because nothing is foreign.',
		},
		owner: 'state',
		side: 'red',
		copies: 2
	},
	{
		ability: {
			key: 'sleeper',
			name: 'Sleeper Implant',
			kind: 'implant',
			skill: 'opsec',
			ap: 2,
			mod: 1,
			noise: 0,
			text: 'Dormant and inert. Cannot be found by a sweep for 2 rounds — there is nothing running to find.',
		},
		owner: 'state',
		side: 'red',
		copies: 2
	},
	{
		ability: {
			key: 'ca',
			name: 'Certificate Pressure',
			kind: 'control',
			skill: 'social',
			ap: 2,
			mod: 0,
			noise: 1,
			dc: 9,
			targets: ['checkpoint', 'court'],
			text: 'A cooperative authority signs. The Checkpoint loses 4 hardening this round: the traffic is valid.',
		},
		owner: 'state',
		side: 'red',
		copies: 2
	},
	{
		ability: {
			key: 'harden',
			name: 'Harden',
			kind: 'control',
			skill: 'tech',
			ap: 1,
			mod: 0,
			noise: 0,
			dc: 6,
			on: ['blue', 'neutral'],
			text: 'Spend budget on one building: +3 hardening, permanently. Slow, unglamorous, and how the game is actually won.',
		},
		owner: 'architect',
		side: 'blue',
		copies: 3
	},
	{
		ability: {
			key: 'attest',
			name: 'Provenance Attestation',
			kind: 'recon',
			skill: 'analysis',
			ap: 2,
			mod: 0,
			noise: 0,
			dc: 9,
			targets: ['forge', 'silos', 'court'],
			on: ['blue', 'neutral'],
			text: 'Sign the whole chain from source to artifact. Any divergence between the two is revealed outright.',
		},
		owner: 'architect',
		side: 'blue',
		copies: 2
	},
	{
		ability: {
			key: 'rebuild',
			name: 'Rebuild From Source',
			kind: 'control',
			skill: 'tech',
			ap: 3,
			mod: 0,
			noise: 0,
			dc: 8,
			on: ['blue', 'neutral'],
			text: 'Throw the artifact away and make it again from readable source. Evicts any non-persistent foothold in the Foundry.',
		},
		owner: 'architect',
		side: 'blue',
		copies: 2
	},
	{
		ability: {
			key: 'sweep',
			name: 'Sweep',
			kind: 'recon',
			skill: 'analysis',
			ap: 1,
			mod: 0,
			noise: 0,
			dc: 7,
			on: ['blue', 'neutral'],
			text: 'Reveal every active implant in one territory. Sleepers are inert and stay hidden — that is the point of them.',
		},
		owner: 'hunter',
		side: 'blue',
		copies: 3
	},
	{
		ability: {
			key: 'diff',
			name: 'Diff the Tarball',
			kind: 'recon',
			skill: 'analysis',
			ap: 2,
			mod: 0,
			noise: 0,
			dc: 9,
			targets: ['silos', 'forge', 'house', 'mill'],
			on: ['blue', 'neutral'],
			text: 'Compare what shipped against what was written. Reveals Release Divergence outright, wherever it hides.',
		},
		owner: 'hunter',
		side: 'blue',
		copies: 2
	},
	{
		ability: {
			key: 'quarantine',
			name: 'Quarantine',
			kind: 'control',
			skill: 'tech',
			ap: 2,
			mod: 0,
			noise: 0,
			dc: 8,
			on: ['blue', 'neutral'],
			text: 'A building goes dark for 2 rounds. Anything held inside it cannot advance the chain.',
		},
		owner: 'hunter',
		side: 'blue',
		copies: 2
	},
];

export const cardByKey = (key: string): CardDef | undefined =>
	CATALOGUE.find((c) => c.ability.key === key);

export const abilityByKey = (key: string): Ability | undefined => cardByKey(key)?.ability;

/** Every card a side can ever hold. */
export const catalogueFor = (side: Faction): CardDef[] =>
	CATALOGUE.filter((c) => c.side === side);

/** A character's own move, if they have one. */
export const powerOf = (klassKey: string): Power | undefined =>
	ROSTER.find((k) => k.key === klassKey)?.power;

/** The card TYPES a seat can ever hold. Not a hand. */
export const abilitiesOf = (klassKey: string): Ability[] =>
	CATALOGUE.filter((c) => c.owner === klassKey).map((c) => c.ability);
